import { $MultiBufferSource_ } from "@package/net/minecraft/client/renderer";
import { $MapCodec } from "@package/com/mojang/serialization";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $TrackMaterial$TrackType } from "@package/com/simibubi/create/content/trains/track";
import { $GameEventListener } from "@package/net/minecraft/world/level/gameevent";
import { $ParticleOptions_, $ParticleOptions } from "@package/net/minecraft/core/particles";
import { $List, $EnumSet, $Map_, $Map, $Set } from "@package/java/util";
import { $AccessorBogeyStyle } from "@package/com/railwayteam/railways/mixin/client";
import { $Carriage } from "@package/com/simibubi/create/content/trains/entity";
import { $InteractionResult, $ItemInteractionResult } from "@package/net/minecraft/world";
import { $Supplier_, $Function_, $Consumer_, $Supplier } from "@package/java/util/function";
import { $ServerLevel } from "@package/net/minecraft/server/level";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $BlockPos_, $Direction_, $Direction$Axis, $Direction, $IdMapper } from "@package/net/minecraft/core";
import { $Object2ByteLinkedOpenHashMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $StateDefinition, $BlockBehaviour$Properties, $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $ProperWaterloggedBlock, $IBE } from "@package/com/simibubi/create/foundation/block";
import { $Record, $ThreadLocal } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $LevelAccessor, $BlockGetter, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemRequirement } from "@package/com/simibubi/create/content/schematics/requirement";
import { $SpecialBlockItemRequirement } from "@package/com/simibubi/create/api/schematic/requirement";
import { $Item, $ItemStack } from "@package/net/minecraft/world/item";
import { $VisualizationContext } from "@package/dev/engine_room/flywheel/api/visualization";
import { $FluidState, $Fluid_ } from "@package/net/minecraft/world/level/material";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $EnumProperty, $Property } from "@package/net/minecraft/world/level/block/state/properties";
import { $IWrenchable } from "@package/com/simibubi/create/content/equipment/wrench";
import { $BlockPlaceContext, $UseOnContext } from "@package/net/minecraft/world/item/context";
import { $ResourceLocation_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $Block$BlockStatePairKey, $SoundType, $Block } from "@package/net/minecraft/world/level/block";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $BlockEntityTicker, $BlockEntityType_, $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/com/simibubi/create/content/trains/bogey" {
    export class $AbstractBogeyBlock<T extends $AbstractBogeyBlockEntity> extends $Block implements $IBE<T>, $ProperWaterloggedBlock, $SpecialBlockItemRequirement, $IWrenchable {
        getSize(): $BogeySizes$BogeySize;
        getVersion(arg0: $BlockState_, arg1: boolean): $BlockState;
        getRequiredItems(arg0: $BlockState_, arg1: $BlockEntity): $ItemRequirement;
        isOnIncompatibleTrack(arg0: $Carriage, arg1: boolean): boolean;
        getTrackType(arg0: $BogeyStyle): $TrackMaterial$TrackType;
        getValidPathfindingTypes(arg0: $BogeyStyle): $Set<$TrackMaterial$TrackType>;
        static registerStandardBogey(arg0: $ResourceLocation_): void;
        getStickySurfaces(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $BlockState_): $EnumSet<$Direction>;
        getWheelPointSpacing(): number;
        getWheelRadius(): number;
        getConnectorAnchorOffset(arg0: boolean): $Vec3;
        allowsSingleBogeyCarriage(): boolean;
        captureBlockEntityForTrain(): boolean;
        getBogeyUpDirection(): $Direction;
        isTrackAxisAlongFirstCoordinate(arg0: $BlockState_): boolean;
        getMatchingBogey(arg0: $Direction_, arg1: boolean): $BlockState;
        getNextStyle(arg0: $Level_, arg1: $BlockPos_): $BogeyStyle;
        getNextStyle(arg0: $BogeyStyle): $BogeyStyle;
        getStateOfSize(arg0: $AbstractBogeyBlockEntity, arg1: $BogeySizes$BogeySize_): $BlockState;
        getNextSize(arg0: $AbstractBogeyBlockEntity): $BlockState;
        getNextSize(arg0: $Level_, arg1: $BlockPos_): $BlockState;
        propertiesToCopy(): $List<$Property<never>>;
        canBeUpsideDown(): boolean;
        isUpsideDown(arg0: $BlockState_): boolean;
        getRotatedBlockState(arg0: $BlockState_, arg1: $Direction_): $BlockState;
        getDefaultStyle(): $BogeyStyle;
        onBlockEntityUse(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<T, $InteractionResult>): $InteractionResult;
        onBlockEntityUseItemOn(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<T, $ItemInteractionResult>): $ItemInteractionResult;
        withBlockEntityDo(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Consumer_<T>): void;
        getBlockEntityOptional(arg0: $BlockGetter, arg1: $BlockPos_): (T) | undefined;
        newBlockEntity(arg0: $BlockPos_, arg1: $BlockState_): $BlockEntity;
        getBlockEntity(arg0: $BlockGetter, arg1: $BlockPos_): T;
        getTicker<S extends $BlockEntity>(arg0: $Level_, arg1: $BlockState_, arg2: $BlockEntityType_<S>): $BlockEntityTicker<S>;
        withWater(arg0: $BlockState_, arg1: $BlockPlaceContext): $BlockState;
        updateWater(arg0: $LevelAccessor, arg1: $BlockState_, arg2: $BlockPos_): void;
        fluidState(arg0: $BlockState_): $FluidState;
        updateAfterWrenched(arg0: $BlockState_, arg1: $UseOnContext): $BlockState;
        onWrenched(arg0: $BlockState_, arg1: $UseOnContext): $InteractionResult;
        onSneakWrenched(arg0: $BlockState_, arg1: $UseOnContext): $InteractionResult;
        getListener<T extends $BlockEntity>(arg0: $ServerLevel, arg1: T): $GameEventListener;
        getPickupSound(): ($SoundEvent) | undefined;
        placeLiquid(arg0: $LevelAccessor, arg1: $BlockPos_, arg2: $BlockState_, arg3: $FluidState): boolean;
        pickupBlock(arg0: $Player, arg1: $LevelAccessor, arg2: $BlockPos_, arg3: $BlockState_): $ItemStack;
        canPlaceLiquid(arg0: $Player, arg1: $BlockGetter, arg2: $BlockPos_, arg3: $BlockState_, arg4: $Fluid_): boolean;
        getPickupSound(arg0: $BlockState_): ($SoundEvent) | undefined;
        explosionResistance: number;
        static UPDATE_SHAPE_ORDER: $Direction[];
        static OCCLUSION_CACHE: $ThreadLocal<$Object2ByteLinkedOpenHashMap<$Block$BlockStatePairKey>>;
        static UPDATE_NONE: number;
        static UPDATE_INVISIBLE: number;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $AbstractBogeyBlock<never>>;
        stateDefinition: $StateDefinition<$Block, $BlockState>;
        static UPDATE_MOVE_BY_PISTON: number;
        static UPDATE_LIMIT: number;
        static UPDATE_ALL: number;
        drops: $ResourceKey<$LootTable>;
        static UPDATE_KNOWN_SHAPE: number;
        static UPDATE_SUPPRESS_DROPS: number;
        dynamicShape: boolean;
        soundType: $SoundType;
        jumpFactor: number;
        static UPDATE_IMMEDIATE: number;
        item: $Item;
        static CODEC: $MapCodec<$Block>;
        static UPDATE_NEIGHBORS: number;
        static INDESTRUCTIBLE: number;
        speedFactor: number;
        friction: number;
        static BLOCK_STATE_REGISTRY: $IdMapper<$BlockState>;
        static UPDATE_ALL_IMMEDIATE: number;
        size: $BogeySizes$BogeySize;
        static INSTANT: number;
        static UPDATE_CLIENTS: number;
        hasCollision: boolean;
        static AXIS: $EnumProperty<$Direction$Axis>;
        constructor(arg0: $BlockBehaviour$Properties, arg1: $BogeySizes$BogeySize_);
        get wheelPointSpacing(): number;
        get wheelRadius(): number;
        get bogeyUpDirection(): $Direction;
        get defaultStyle(): $BogeyStyle;
    }
    export class $BogeySizes$BogeySize extends $Record {
        id(): $ResourceLocation;
        nextBySize(): $BogeySizes$BogeySize;
        wheelRadius(): number;
        constructor(id: $ResourceLocation_, wheelRadius: number);
    }
    /**
     * Values that may be interpreted as {@link $BogeySizes$BogeySize}.
     */
    export type $BogeySizes$BogeySize_ = { id?: $ResourceLocation_, wheelRadius?: number,  } | [id?: $ResourceLocation_, wheelRadius?: number, ];
    export class $BogeyStyle implements $AccessorBogeyStyle {
        createVisual(arg0: $BogeySizes$BogeySize_, arg1: $VisualizationContext, arg2: number, arg3: boolean): $BogeyVisual;
        validSizes(): $Set<$BogeySizes$BogeySize>;
        getBlockForSize(arg0: $BogeySizes$BogeySize_): $AbstractBogeyBlock<never>;
        getNextBlock(arg0: $BogeySizes$BogeySize_): $AbstractBogeyBlock<never>;
        getCycleGroup(): $Map<$ResourceLocation, $BogeyStyle>;
        render(arg0: $BogeySizes$BogeySize_, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: number, arg5: number, arg6: number, arg7: $CompoundTag_, arg8: boolean): void;
        getSizeRenderers(): $Map<$BogeySizes$BogeySize, $BogeyStyle$SizeRenderer>;
        contactParticle: $ParticleOptions;
        soundEvent: $Supplier<$SoundEvent>;
        smokeParticle: $ParticleOptions;
        cycleGroup: $ResourceLocation;
        displayName: $Component;
        defaultData: $CompoundTag;
        id: $ResourceLocation;
        constructor(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $Component_, arg3: $Supplier_<$SoundEvent>, arg4: $ParticleOptions_, arg5: $ParticleOptions_, arg6: $CompoundTag_, arg7: $Map_<$BogeySizes$BogeySize_, $Supplier_<$AbstractBogeyBlock<never>>>, arg8: $Map_<$BogeySizes$BogeySize_, $Supplier_<$Supplier<$BogeyStyle$SizeRenderer>>>);
        get sizeRenderers(): $Map<$BogeySizes$BogeySize, $BogeyStyle$SizeRenderer>;
    }
}
