import { $File_, $File } from "@package/java/io";
import { $Codec } from "@package/com/mojang/serialization";
import { $Pair } from "@package/com/mojang/datafixers/util";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Component } from "@package/net/minecraft/network/chat";
import { $IGuiTexture, $IGuiTexture_ } from "@package/com/lowdragmc/lowdraglib2/gui/texture";
import { $InspectorView, $HistoryView, $ResourceView } from "@package/com/lowdragmc/lowdraglib2/editor/ui/view";
import { $TreeNode, $TreeBuilder$Menu } from "@package/com/lowdragmc/lowdraglib2/gui/util";
import { $IProject } from "@package/com/lowdragmc/lowdraglib2/editor/project";
import { $List, $LinkedHashMap } from "@package/java/util";
import { $EditorSettings } from "@package/com/lowdragmc/lowdraglib2/editor/settings";
import { $Tab, $Menu, $SplitView, $TabView, $Button } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements";
import { $UIElementProvider_ } from "@package/com/lowdragmc/lowdraglib2/gui/ui/utils";
import { $Consumer_, $Supplier_ } from "@package/java/util/function";
import { $YogaEdge_ } from "@package/org/appliedenergistics/yoga";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Style, $UIElement } from "@package/com/lowdragmc/lowdraglib2/gui/ui";
import { $ViewMenu, $FileMenu } from "@package/com/lowdragmc/lowdraglib2/editor/ui/menu";
import { $Layout } from "@package/dev/vfyjxf/taffy/tree";
import { $Runnable_, $Record } from "@package/java/lang";
export * as menu from "@package/com/lowdragmc/lowdraglib2/editor/ui/menu";
export * as view from "@package/com/lowdragmc/lowdraglib2/editor/ui/view";
export * as resource from "@package/com/lowdragmc/lowdraglib2/editor/ui/resource";

declare module "@package/com/lowdragmc/lowdraglib2/editor/ui" {
    export class $SplittableWindow$LayoutConfig extends $Record {
        first(): $SplittableWindow$LayoutConfig;
        second(): $SplittableWindow$LayoutConfig;
        static deserialize(arg0: $CompoundTag_): $SplittableWindow$LayoutConfig;
        serialize(): $CompoundTag;
        percentage(): number;
        constructor(percentage: number, first: $SplittableWindow$LayoutConfig_, second: $SplittableWindow$LayoutConfig_);
    }
    /**
     * Values that may be interpreted as {@link $SplittableWindow$LayoutConfig}.
     */
    export type $SplittableWindow$LayoutConfig_ = { second?: $SplittableWindow$LayoutConfig_, percentage?: number, first?: $SplittableWindow$LayoutConfig_,  } | [second?: $SplittableWindow$LayoutConfig_, percentage?: number, first?: $SplittableWindow$LayoutConfig_, ];
    export class $View extends $UIElement {
        getName(): string;
        setName(arg0: string): void;
        createTab(): $Tab;
        setCanRemove(arg0: boolean): void;
        getViewContainer(): $ViewContainer;
        isCanRemove(): boolean;
        setOnRemove(arg0: $Runnable_): void;
        setDynamicName(arg0: $Supplier_<$Component>): void;
        getIcon(): $IGuiTexture;
        setIcon(arg0: $IGuiTexture_): void;
        static CODEC: $Codec<$UIElement>;
        static EMPTY_LAYOUT: $Layout;
        constructor(arg0: string, arg1: $IGuiTexture_);
        constructor(arg0: string);
        constructor();
        get viewContainer(): $ViewContainer;
        set onRemove(value: $Runnable_);
        set dynamicName(value: $Supplier_<$Component>);
    }
    export class $ViewContainer extends $UIElement {
        expand(): void;
        isCollapse(): boolean;
        collapse(): void;
        addView(arg0: $View): $ViewContainer;
        addViews(...arg0: $View[]): $ViewContainer;
        getAllViews(): $List<$View>;
        isEmptyWindow(): boolean;
        hasView(arg0: $View): boolean;
        selectView(arg0: $View): void;
        removeView(arg0: $View): void;
        addViewAt(arg0: $View, arg1: number): $ViewContainer;
        isViewSelected(arg0: $View): boolean;
        getWindow(): $SplittableWindow;
        buttonIcon: $UIElement;
        static CODEC: $Codec<$UIElement>;
        collapseButton: $Button;
        static EMPTY_LAYOUT: $Layout;
        tabView: $TabView;
        constructor();
        get allViews(): $List<$View>;
        get emptyWindow(): boolean;
        get window(): $SplittableWindow;
    }
    export class $EditorWindow extends $UIElement {
        static open(arg0: $ResourceLocation_, arg1: $Supplier_<$Editor>): $EditorWindow;
        closeWindow(): void;
        createNewEditor(arg0: $Supplier_<$Editor>): $Editor;
        removeEditor(arg0: $Editor): void;
        hasMultipleEditors(): boolean;
        showEditor(arg0: $Editor): void;
        isMaximized(): boolean;
        retoreWindow(): void;
        maximizeWindow(): void;
        minimizeWindow(): void;
        getCurrentEditor(): $Editor;
        getEditors(): $LinkedHashMap<$Editor, $UIElement>;
        static openDefault(arg0: $Supplier_<$Editor>): $EditorWindow;
        editorButtonContainer: $UIElement;
        static CODEC: $Codec<$UIElement>;
        static DEFAULT_ID: $ResourceLocation;
        editorContainer: $UIElement;
        static EMPTY_LAYOUT: $Layout;
        window: $UIElement;
        windowID: $ResourceLocation;
        constructor(arg0: $ResourceLocation_, arg1: $Supplier_<$Editor>);
        constructor(arg0: $Supplier_<$Editor>);
        get maximized(): boolean;
        get currentEditor(): $Editor;
        get editors(): $LinkedHashMap<$Editor, $UIElement>;
    }
    export class $Editor extends $UIElement {
        exit(): void;
        exit(arg0: $Runnable_): void;
        close(): void;
        getAllViews(): $List<$View>;
        askToSaveProject(arg0: $Runnable_): void;
        isCurrentProjectDirty(): boolean;
        saveProject(arg0: $Runnable_, arg1: boolean): void;
        saveProject(arg0: $Runnable_): void;
        saveAsProject(arg0: $Runnable_): void;
        closeCurrentProject(arg0: boolean, arg1: $Runnable_): void;
        getCurrentProject(): $IProject;
        getCurrentProjectFile(): $File;
        openSettingsPanel(): void;
        loadProject(arg0: $IProject, arg1: $File_): void;
        static emptyEditor(): $Editor;
        getTop(): $UIElement;
        getMenuContainer(): $UIElement;
        getTopPlaceholder(): $UIElement;
        getButtonContainer(): $UIElement;
        getCloseButton(): $Button;
        getFileMenu(): $FileMenu;
        getViewMenu(): $ViewMenu;
        getMainView(): $UIElement;
        getRootWindow(): $SplittableWindow;
        getLeftWindow(): $SplittableWindow;
        getRightWindow(): $SplittableWindow;
        getCenterWindow(): $SplittableWindow;
        getBottomWindow(): $SplittableWindow;
        getInspectorView(): $InspectorView;
        getResourceView(): $ResourceView;
        getHistoryView(): $HistoryView;
        getEditorSettings(): $EditorSettings;
        getIcon(): $UIElement;
        getTitle(): $Component;
        getWindow(): $EditorWindow;
        openMenu<T, C>(arg0: number, arg1: number, arg2: $TreeNode<T, C>, arg3: $UIElementProvider_<T>): $Menu<T, C>;
        openMenu(arg0: number, arg1: number, arg2: $TreeBuilder$Menu): void;
        leftWindow: $SplittableWindow;
        static CODEC: $Codec<$UIElement>;
        resourceView: $ResourceView;
        historyView: $HistoryView;
        static EMPTY_LAYOUT: $Layout;
        topPlaceholder: $UIElement;
        viewMenu: $ViewMenu;
        icon: $UIElement;
        centerWindow: $SplittableWindow;
        menuContainer: $UIElement;
        buttonContainer: $UIElement;
        editorSettings: $EditorSettings;
        inspectorView: $InspectorView;
        rightWindow: $SplittableWindow;
        top: $UIElement;
        rootWindow: $SplittableWindow;
        bottomWindow: $SplittableWindow;
        closeButton: $Button;
        fileMenu: $FileMenu;
        mainView: $UIElement;
        constructor();
        get allViews(): $List<$View>;
        get currentProjectDirty(): boolean;
        get currentProject(): $IProject;
        get currentProjectFile(): $File;
        get title(): $Component;
        get window(): $EditorWindow;
    }
    export class $SplittableWindow extends $UIElement {
        getFirst(): $SplittableWindow;
        getSecond(): $SplittableWindow;
        setImmortal(arg0: boolean): $SplittableWindow;
        splitStyle(arg0: $Consumer_<$SplittableWindow$SplitStyle>): $SplittableWindow;
        splitNew(arg0: $YogaEdge_): $Pair<$SplittableWindow, $SplittableWindow>;
        getRightTop(): $ViewContainer;
        getLeftBottom(): $ViewContainer;
        getAllViews(): $List<$View>;
        getLeftTop(): $ViewContainer;
        getRightBottom(): $ViewContainer;
        splitWith(arg0: $YogaEdge_, arg1: $SplittableWindow): $Pair<$SplittableWindow, $SplittableWindow>;
        getViewContainer(): $ViewContainer;
        removeSplitWindow(arg0: $SplittableWindow): void;
        getSplitStyle(): $SplittableWindow$SplitStyle;
        getParentWindow(): $SplittableWindow;
        setParentWindow(arg0: $SplittableWindow): $SplittableWindow;
        isImmortal(): boolean;
        getSplitView(): $SplitView;
        setViewContainer(arg0: $ViewContainer): $SplittableWindow;
        getLayoutConfig(): $SplittableWindow$LayoutConfig;
        applyLayoutConfig(arg0: $SplittableWindow$LayoutConfig_): $SplittableWindow;
        isSplit(): boolean;
        static CODEC: $Codec<$UIElement>;
        static EMPTY_LAYOUT: $Layout;
        constructor(arg0: $SplittableWindow, arg1: $ViewContainer);
        constructor(arg0: $SplittableWindow);
        constructor();
        get first(): $SplittableWindow;
        get second(): $SplittableWindow;
        get rightTop(): $ViewContainer;
        get leftBottom(): $ViewContainer;
        get allViews(): $List<$View>;
        get leftTop(): $ViewContainer;
        get rightBottom(): $ViewContainer;
        get splitView(): $SplitView;
        get layoutConfig(): $SplittableWindow$LayoutConfig;
        get split(): boolean;
    }
    export class $SplittableWindow$SplitStyle extends $Style {
        static init(): void;
        minPercentage(): number;
        minPercentage(arg0: number): $SplittableWindow$SplitStyle;
        maxPercentage(): number;
        maxPercentage(arg0: number): $SplittableWindow$SplitStyle;
        percentage(): number;
        percentage(arg0: number): $SplittableWindow$SplitStyle;
        holder: $UIElement;
        constructor(arg0: $SplittableWindow);
    }
}
