import { $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $UUID } from "@package/java/util";
import { $BackpackTraits } from "@package/com/beansgalaxy/backpacks/traits/backpack";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SynchedEntityData, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $IEntityTraits } from "@package/com/beansgalaxy/backpacks/traits";
import { $InteractionResult, $InteractionHand_ } from "@package/net/minecraft/world";
import { $Supplier_ } from "@package/java/util/function";
import { $BlockPos, $Direction_, $Direction } from "@package/net/minecraft/core";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $UseOnContext } from "@package/net/minecraft/world/item/context";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $DataComponentType_ } from "@package/net/minecraft/core/component";
import { $ViewableBackpack, $ComponentHolder } from "@package/com/beansgalaxy/backpacks/util";
import { $Vec3_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";

declare module "@package/com/beansgalaxy/backpacks/traits/common" {
    export class $BackpackEntity extends $Entity implements $ComponentHolder {
        getTraits(): $IEntityTraits<never>;
        toStack(): $ItemStack;
        hop(arg0: number): void;
        setDirection(arg0: $Direction_): void;
        tryEquip(arg0: $Player): $InteractionResult;
        useTraitInteraction(arg0: $Player, arg1: $InteractionHand_): $InteractionResult;
        remove<T>(arg0: $DataComponentType_<T>): T;
        get<T>(arg0: $DataComponentType_<T>): T;
        set<T>(arg0: $DataComponentType_<T>, arg1: T): void;
        static create(arg0: $ItemStack_, arg1: $BackpackTraits, arg2: $Level_, arg3: $Vec3_, arg4: number, arg5: $Direction_, arg6: $Player): $BackpackEntity;
        static create(arg0: $UseOnContext, arg1: $ItemStack_, arg2: $BackpackTraits): $BackpackEntity;
        static drop(arg0: $Player): void;
        wobble(arg0: number): void;
        setChanged(): void;
        has(arg0: $DataComponentType_<never>): boolean;
        getOrDefault<T>(arg0: $DataComponentType_<T>, arg1: T): T;
        getOrElse<T>(arg0: $DataComponentType_<T>, arg1: $Supplier_<T>): T;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        static BACKPACK_HEALTH: number;
        noPhysics: boolean;
        yo: number;
        static IS_OPEN: $EntityDataAccessor<boolean>;
        static ITEM_STACK: $EntityDataAccessor<$ItemStack>;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        viewable: $ViewableBackpack;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        breakAmount: number;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        static DIRECTION: $EntityDataAccessor<$Direction>;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<never>, arg1: $Level_);
        get traits(): $IEntityTraits<never>;
        set direction(value: $Direction_);
    }
}
