[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true

[stackGroups]
	enableStackGroups = true
	disabledStackGroups = ["minecraft:flowers", "minecraft:beds", "c:buckets"]
