import { $Instant, $Duration_ } from "@package/java/time";
import { $UnaryOperator_ } from "@package/java/util/function";
import { $OptionalString, $HTTPConnection, $StatusCode } from "@package/dev/latvian/apps/tinyserver";
import { $Path_ } from "@package/java/nio/file";
import { $HTTPRequest, $HTTPUpgrade } from "@package/dev/latvian/apps/tinyserver/http";
import { $DateTimeFormatter } from "@package/java/time/format";
import { $List } from "@package/java/util";
import { $CharSequence, $Iterable_, $Enum, $Object } from "@package/java/lang";
import { $BufferedImage } from "@package/java/awt/image";
import { $ByteBuffer } from "@package/java/nio";
import { $ResponseContentEncoding } from "@package/dev/latvian/apps/tinyserver/http/response/encoding";
import { $ResponseContent, $ResponseContent_ } from "@package/dev/latvian/apps/tinyserver/content";
export * as encoding from "@package/dev/latvian/apps/tinyserver/http/response/encoding";

declare module "@package/dev/latvian/apps/tinyserver/http/response" {
    export class $HTTPResponse {
        static created(): $HTTPResponse;
        static ok(): $HTTPResponse;
        static redirect(location: string): $HTTPResponse;
        static accepted(): $HTTPResponse;
        static noContent(): $HTTPResponse;
        static movedPermanently(location: string): $HTTPResponse;
        static redirectTemporary(location: string): $HTTPResponse;
        static redirectPermanently(location: string): $HTTPResponse;
        static upgrade(upgrade: $HTTPUpgrade<never>): $HTTPResponse;
    }
    export interface $HTTPResponse {
        cache(isPublic: boolean, duration: $Duration_): $HTTPResponse;
        status(): $HTTPStatus;
        encoding(encoding: $ResponseContentEncoding): $HTTPResponse;
        build(payload: $HTTPPayload): void;
        text(text: $Iterable_<string>): $HTTPResponse;
        text(text: string): $HTTPResponse;
        content(content: $ResponseContent_): $HTTPResponse;
        content(bytes: number[], type: string): $HTTPResponse;
        content(string: $CharSequence, type: string): $HTTPResponse;
        content(file: $Path_): $HTTPResponse;
        content(file: $Path_, overrideType: string): $HTTPResponse;
        header(header: string, value: $Object): $HTTPResponse;
        publicCache(duration: $Duration_): $HTTPResponse;
        cors(): $HTTPResponse;
        cors(value: string): $HTTPResponse;
        gzip(): $HTTPResponse;
        removeCookie(key: string): $HTTPResponse;
        noCache(): $HTTPResponse;
        privateCache(duration: $Duration_): $HTTPResponse;
        jpeg(img: $BufferedImage): $HTTPResponse;
        png(img: $BufferedImage): $HTTPResponse;
        html(text: string): $HTTPResponse;
        cookie(key: string, value: string, properties: $UnaryOperator_<$CookieResponse$Builder>): $HTTPResponse;
        cookie(key: string, value: string): $HTTPResponse;
        deflate(): $HTTPResponse;
        json(json: string): $HTTPResponse;
    }
    export class $HTTPStatus extends $Enum<$HTTPStatus> implements $HTTPResponse {
        static values(): $HTTPStatus[];
        static valueOf(name: string): $HTTPStatus;
        code(): number;
        status(): $HTTPStatus;
        build(payload: $HTTPPayload): void;
        error(): boolean;
        redirect(): boolean;
        statusCode(): $StatusCode;
        defaultResponse(): $HTTPResponse;
        informational(): boolean;
        clientError(): boolean;
        serverError(): boolean;
        success(): boolean;
        static fromCode(code: number): $HTTPStatus;
        responseBuffer(): $ByteBuffer;
        cache(isPublic: boolean, duration: $Duration_): $HTTPResponse;
        encoding(encoding: $ResponseContentEncoding): $HTTPResponse;
        text(text: $Iterable_<string>): $HTTPResponse;
        text(text: string): $HTTPResponse;
        content(content: $ResponseContent_): $HTTPResponse;
        content(bytes: number[], type: string): $HTTPResponse;
        content(string: $CharSequence, type: string): $HTTPResponse;
        content(file: $Path_): $HTTPResponse;
        content(file: $Path_, overrideType: string): $HTTPResponse;
        header(header: string, value: $Object): $HTTPResponse;
        publicCache(duration: $Duration_): $HTTPResponse;
        cors(): $HTTPResponse;
        cors(value: string): $HTTPResponse;
        gzip(): $HTTPResponse;
        removeCookie(key: string): $HTTPResponse;
        noCache(): $HTTPResponse;
        privateCache(duration: $Duration_): $HTTPResponse;
        jpeg(img: $BufferedImage): $HTTPResponse;
        png(img: $BufferedImage): $HTTPResponse;
        html(text: string): $HTTPResponse;
        cookie(key: string, value: string, properties: $UnaryOperator_<$CookieResponse$Builder>): $HTTPResponse;
        cookie(key: string, value: string): $HTTPResponse;
        deflate(): $HTTPResponse;
        json(json: string): $HTTPResponse;
        static ALL: $List<$HTTPStatus>;
        static REQUEST_TIMEOUT: $HTTPStatus;
        static USE_PROXY: $HTTPStatus;
        static TEMPORARY_REDIRECT: $HTTPStatus;
        static CLIENT_ERROR: $List<$HTTPStatus>;
        static NOT_AUTHORITATIVE_INFORMATION: $HTTPStatus;
        static ACCEPTED: $HTTPStatus;
        static BAD_GATEWAY: $HTTPStatus;
        static URI_TOO_LONG: $HTTPStatus;
        static NOT_ACCEPTABLE: $HTTPStatus;
        static RESET_CONTENT: $HTTPStatus;
        static PARTIAL_CONTENT: $HTTPStatus;
        static RANGE_NOT_SATISFIABLE: $HTTPStatus;
        static GATEWAY_TIMEOUT: $HTTPStatus;
        static FOUND: $HTTPStatus;
        static UNPROCESSABLE_CONTENT: $HTTPStatus;
        static METHOD_NOT_ALLOWED: $HTTPStatus;
        static EXPECTATION_FAILED: $HTTPStatus;
        static NOT_FOUND: $HTTPStatus;
        static PERMANENT_REDIRECT: $HTTPStatus;
        static LENGTH_REQUIRED: $HTTPStatus;
        static MULTIPLE_CHOICES: $HTTPStatus;
        static SWITCHING_PROTOCOLS: $HTTPStatus;
        static GONE: $HTTPStatus;
        static REDIRECT: $List<$HTTPStatus>;
        static UPGRADE_REQUIRED: $HTTPStatus;
        static CONFLICT: $HTTPStatus;
        static HTTP_VERSION_NOT_SUPPORTED: $HTTPStatus;
        static UNSUPPORTED_MEDIA_TYPE: $HTTPStatus;
        static NO_CONTENT: $HTTPStatus;
        static PROXY_AUTHENTICATION_REQUIRED: $HTTPStatus;
        static PAYMENT_REQUIRED: $HTTPStatus;
        static CREATED: $HTTPStatus;
        static SERVER_ERROR: $List<$HTTPStatus>;
        static MOVED_PERMANENTLY: $HTTPStatus;
        static LOOKUP: $List<$List<$HTTPStatus>>;
        static UNAUTHORIZED: $HTTPStatus;
        static CONTENT_TOO_LARGE: $HTTPStatus;
        static OK: $HTTPStatus;
        static SUCCESS: $List<$HTTPStatus>;
        static BAD_REQUEST: $HTTPStatus;
        static INTERNAL_ERROR: $HTTPStatus;
        static MISDIRECTED_REQUEST: $HTTPStatus;
        static SEE_OTHER: $HTTPStatus;
        static FORBIDDEN: $HTTPStatus;
        static CONTINUE: $HTTPStatus;
        static NOT_MODIFIED: $HTTPStatus;
        static NOT_IMPLEMENTED: $HTTPStatus;
        static PRECONDITION_FAILED: $HTTPStatus;
        static SERVICE_UNAVAILABLE: $HTTPStatus;
        static INFORMATIONAL: $List<$HTTPStatus>;
    }
    /**
     * Values that may be interpreted as {@link $HTTPStatus}.
     */
    export type $HTTPStatus_ = "continue" | "switching_protocols" | "ok" | "created" | "accepted" | "not_authoritative_information" | "no_content" | "reset_content" | "partial_content" | "multiple_choices" | "moved_permanently" | "found" | "see_other" | "not_modified" | "use_proxy" | "temporary_redirect" | "permanent_redirect" | "bad_request" | "unauthorized" | "payment_required" | "forbidden" | "not_found" | "method_not_allowed" | "not_acceptable" | "proxy_authentication_required" | "request_timeout" | "conflict" | "gone" | "length_required" | "precondition_failed" | "content_too_large" | "uri_too_long" | "unsupported_media_type" | "range_not_satisfiable" | "expectation_failed" | "misdirected_request" | "unprocessable_content" | "upgrade_required" | "internal_error" | "not_implemented" | "bad_gateway" | "service_unavailable" | "gateway_timeout" | "http_version_not_supported";
    export class $CookieResponse$Builder {
        remove(): $CookieResponse$Builder;
        comment(comment: string): $CookieResponse$Builder;
        path(path: string): $CookieResponse$Builder;
        session(): $CookieResponse$Builder;
        partitioned(partitioned: boolean): $CookieResponse$Builder;
        httpOnly(): $CookieResponse$Builder;
        sameSite(sameSite: string): $CookieResponse$Builder;
        maxAgeYear(): $CookieResponse$Builder;
        maxAge(maxAge: number): $CookieResponse$Builder;
        secure(): $CookieResponse$Builder;
        domain(domain: string): $CookieResponse$Builder;
        constructor();
    }
    export class $HTTPPayload {
        clear(): void;
        write(connection: $HTTPConnection<never>, writeBody: boolean): void;
        process(req: $HTTPRequest, keepAliveTimeout: number, maxKeepAliveConnections: number): void;
        getHeader(header: string): $OptionalString;
        setStatus(status: $HTTPStatus_): void;
        addHeader(header: string, value: $Object): void;
        getUpgrade(): $HTTPUpgrade<never>;
        setResponse(response: $HTTPResponse): void;
        getCookie(key: string): string;
        getStatus(): $HTTPStatus;
        getBody(): $ResponseContent;
        setBody(body: $ResponseContent_): void;
        setHeader(header: string, value: $Object): void;
        setCacheControl(cacheControl: string): void;
        getCacheControl(): string;
        setCors(cors: string): void;
        getCors(): string;
        setCookie(key: string, value: string): void;
        setUpgrade(upgrade: $HTTPUpgrade<never>): void;
        addEncoding(encoding: $ResponseContentEncoding): void;
        static DATE_TIME_FORMATTER: $DateTimeFormatter;
        constructor(serverName: string, serverTime: $Instant);
        set response(value: $HTTPResponse);
    }
}
