import { $IntStream } from "@package/java/util/stream";
import { $Comparable, $Object, $Appendable, $CharSequence, $Readable } from "@package/java/lang";
export * as channels from "@package/java/nio/channels";
export * as file from "@package/java/nio/file";
export * as charset from "@package/java/nio/charset";

declare module "@package/java/nio" {
    export class $DoubleBuffer extends $Buffer implements $Comparable<$DoubleBuffer> {
        get(): number;
        get(arg0: number, arg1: number[]): $DoubleBuffer;
        get(arg0: number): number;
        get(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        get(arg0: number[]): $DoubleBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $DoubleBuffer;
        put(arg0: $DoubleBuffer): $DoubleBuffer;
        put(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        put(arg0: number[]): $DoubleBuffer;
        put(arg0: number, arg1: $DoubleBuffer, arg2: number, arg3: number): $DoubleBuffer;
        put(arg0: number, arg1: number[]): $DoubleBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $DoubleBuffer;
        put(arg0: number, arg1: number): $DoubleBuffer;
        put(arg0: number): $DoubleBuffer;
        compareTo(arg0: $DoubleBuffer): number;
        static wrap(arg0: number[]): $DoubleBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $DoubleBuffer;
        mismatch(arg0: $DoubleBuffer): number;
        limit(arg0: number): $DoubleBuffer;
        array(): number[];
        flip(): $DoubleBuffer;
        duplicate(): $DoubleBuffer;
        static allocate(arg0: number): $DoubleBuffer;
        asReadOnlyBuffer(): $DoubleBuffer;
        compact(): $DoubleBuffer;
        order(): $ByteOrder;
    }
    export class $ByteBuffer extends $Buffer implements $Comparable<$ByteBuffer> {
        reset(): $ByteBuffer;
        get(arg0: number[]): $ByteBuffer;
        get(arg0: number): number;
        get(): number;
        get(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        get(arg0: number, arg1: number[]): $ByteBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuffer;
        put(arg0: number, arg1: number): $ByteBuffer;
        put(arg0: $ByteBuffer): $ByteBuffer;
        put(arg0: number, arg1: $ByteBuffer, arg2: number, arg3: number): $ByteBuffer;
        put(arg0: number[]): $ByteBuffer;
        put(arg0: number, arg1: number[]): $ByteBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuffer;
        put(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        put(arg0: number): $ByteBuffer;
        compareTo(arg0: $ByteBuffer): number;
        getShort(): number;
        getShort(arg0: number): number;
        putShort(arg0: number, arg1: number): $ByteBuffer;
        putShort(arg0: number): $ByteBuffer;
        getChar(arg0: number): string;
        getChar(): string;
        putChar(arg0: number, arg1: string): $ByteBuffer;
        putChar(arg0: string): $ByteBuffer;
        getInt(arg0: number): number;
        getInt(): number;
        putInt(arg0: number, arg1: number): $ByteBuffer;
        putInt(arg0: number): $ByteBuffer;
        getLong(arg0: number): number;
        getLong(): number;
        putLong(arg0: number): $ByteBuffer;
        putLong(arg0: number, arg1: number): $ByteBuffer;
        getFloat(): number;
        getFloat(arg0: number): number;
        putFloat(arg0: number): $ByteBuffer;
        putFloat(arg0: number, arg1: number): $ByteBuffer;
        getDouble(arg0: number): number;
        getDouble(): number;
        putDouble(arg0: number, arg1: number): $ByteBuffer;
        putDouble(arg0: number): $ByteBuffer;
        clear(): $ByteBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $ByteBuffer;
        static wrap(arg0: number[]): $ByteBuffer;
        position(arg0: number): $ByteBuffer;
        mismatch(arg0: $ByteBuffer): number;
        flip(): $ByteBuffer;
        slice(arg0: number, arg1: number): $ByteBuffer;
        static allocate(arg0: number): $ByteBuffer;
        alignmentOffset(arg0: number, arg1: number): number;
        static allocateDirect(arg0: number): $ByteBuffer;
        asReadOnlyBuffer(): $ByteBuffer;
        compact(): $ByteBuffer;
        order(arg0: $ByteOrder): $ByteBuffer;
        order(): $ByteOrder;
        alignedSlice(arg0: number): $ByteBuffer;
        asCharBuffer(): $CharBuffer;
        asShortBuffer(): $ShortBuffer;
        asIntBuffer(): $IntBuffer;
        asLongBuffer(): $LongBuffer;
        asFloatBuffer(): $FloatBuffer;
        asDoubleBuffer(): $DoubleBuffer;
    }
    export class $IntBuffer extends $Buffer implements $Comparable<$IntBuffer> {
        get(): number;
        get(arg0: number, arg1: number[]): $IntBuffer;
        get(arg0: number): number;
        get(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        get(arg0: number[]): $IntBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $IntBuffer;
        put(arg0: $IntBuffer): $IntBuffer;
        put(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        put(arg0: number[]): $IntBuffer;
        put(arg0: number, arg1: $IntBuffer, arg2: number, arg3: number): $IntBuffer;
        put(arg0: number, arg1: number[]): $IntBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $IntBuffer;
        put(arg0: number, arg1: number): $IntBuffer;
        put(arg0: number): $IntBuffer;
        compareTo(arg0: $IntBuffer): number;
        static wrap(arg0: number[]): $IntBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $IntBuffer;
        mismatch(arg0: $IntBuffer): number;
        limit(arg0: number): $IntBuffer;
        array(): number[];
        flip(): $IntBuffer;
        duplicate(): $IntBuffer;
        static allocate(arg0: number): $IntBuffer;
        asReadOnlyBuffer(): $IntBuffer;
        compact(): $IntBuffer;
        order(): $ByteOrder;
    }
    export class $ByteOrder {
        static nativeOrder(): $ByteOrder;
        static BIG_ENDIAN: $ByteOrder;
        static LITTLE_ENDIAN: $ByteOrder;
    }
    export class $Buffer {
        reset(): $Buffer;
        clear(): $Buffer;
        position(arg0: number): $Buffer;
        position(): number;
        limit(): number;
        limit(arg0: number): $Buffer;
        remaining(): number;
        isDirect(): boolean;
        hasArray(): boolean;
        array(): $Object;
        arrayOffset(): number;
        capacity(): number;
        mark(): $Buffer;
        flip(): $Buffer;
        rewind(): $Buffer;
        hasRemaining(): boolean;
        isReadOnly(): boolean;
        slice(): $Buffer;
        slice(arg0: number, arg1: number): $Buffer;
        duplicate(): $Buffer;
        get direct(): boolean;
        get readOnly(): boolean;
    }
    export class $FloatBuffer extends $Buffer implements $Comparable<$FloatBuffer> {
        get(): number;
        get(arg0: number, arg1: number[]): $FloatBuffer;
        get(arg0: number): number;
        get(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        get(arg0: number[]): $FloatBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $FloatBuffer;
        put(arg0: $FloatBuffer): $FloatBuffer;
        put(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        put(arg0: number[]): $FloatBuffer;
        put(arg0: number, arg1: $FloatBuffer, arg2: number, arg3: number): $FloatBuffer;
        put(arg0: number, arg1: number[]): $FloatBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $FloatBuffer;
        put(arg0: number, arg1: number): $FloatBuffer;
        put(arg0: number): $FloatBuffer;
        compareTo(arg0: $FloatBuffer): number;
        static wrap(arg0: number[]): $FloatBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $FloatBuffer;
        mismatch(arg0: $FloatBuffer): number;
        limit(arg0: number): $FloatBuffer;
        array(): number[];
        flip(): $FloatBuffer;
        duplicate(): $FloatBuffer;
        static allocate(arg0: number): $FloatBuffer;
        asReadOnlyBuffer(): $FloatBuffer;
        compact(): $FloatBuffer;
        order(): $ByteOrder;
    }
    export class $LongBuffer extends $Buffer implements $Comparable<$LongBuffer> {
        get(): number;
        get(arg0: number, arg1: number[]): $LongBuffer;
        get(arg0: number): number;
        get(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        get(arg0: number[]): $LongBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $LongBuffer;
        put(arg0: $LongBuffer): $LongBuffer;
        put(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        put(arg0: number[]): $LongBuffer;
        put(arg0: number, arg1: $LongBuffer, arg2: number, arg3: number): $LongBuffer;
        put(arg0: number, arg1: number[]): $LongBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $LongBuffer;
        put(arg0: number, arg1: number): $LongBuffer;
        put(arg0: number): $LongBuffer;
        compareTo(arg0: $LongBuffer): number;
        static wrap(arg0: number[]): $LongBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $LongBuffer;
        mismatch(arg0: $LongBuffer): number;
        limit(arg0: number): $LongBuffer;
        array(): number[];
        flip(): $LongBuffer;
        duplicate(): $LongBuffer;
        static allocate(arg0: number): $LongBuffer;
        asReadOnlyBuffer(): $LongBuffer;
        compact(): $LongBuffer;
        order(): $ByteOrder;
    }
    export class $MappedByteBuffer extends $ByteBuffer {
        load(): $MappedByteBuffer;
        clear(): $MappedByteBuffer;
        mark(): $MappedByteBuffer;
        rewind(): $MappedByteBuffer;
        duplicate(): $MappedByteBuffer;
        compact(): $MappedByteBuffer;
        isLoaded(): boolean;
        force(): $MappedByteBuffer;
        force(arg0: number, arg1: number): $MappedByteBuffer;
        get loaded(): boolean;
    }
    export class $CharBuffer extends $Buffer implements $Comparable<$CharBuffer>, $Appendable, $CharSequence, $Readable {
        reset(): $CharBuffer;
        get(arg0: number, arg1: string[], arg2: number, arg3: number): $CharBuffer;
        get(arg0: number, arg1: string[]): $CharBuffer;
        get(): string;
        get(arg0: string[]): $CharBuffer;
        get(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        get(arg0: number): string;
        put(arg0: number, arg1: string): $CharBuffer;
        put(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        put(arg0: number, arg1: $CharBuffer, arg2: number, arg3: number): $CharBuffer;
        put(arg0: $CharBuffer): $CharBuffer;
        put(arg0: string[]): $CharBuffer;
        put(arg0: string): $CharBuffer;
        put(arg0: string, arg1: number, arg2: number): $CharBuffer;
        put(arg0: string): $CharBuffer;
        put(arg0: number, arg1: string[], arg2: number, arg3: number): $CharBuffer;
        put(arg0: number, arg1: string[]): $CharBuffer;
        length(): number;
        getChars(arg0: number, arg1: number, arg2: string[], arg3: number): void;
        compareTo(arg0: $CharBuffer): number;
        clear(): $CharBuffer;
        static wrap(arg0: $CharSequence, arg1: number, arg2: number): $CharBuffer;
        static wrap(arg0: string[]): $CharBuffer;
        static wrap(arg0: $CharSequence): $CharBuffer;
        static wrap(arg0: string[], arg1: number, arg2: number): $CharBuffer;
        position(arg0: number): $CharBuffer;
        charAt(arg0: number): string;
        mismatch(arg0: $CharBuffer): number;
        isEmpty(): boolean;
        limit(arg0: number): $CharBuffer;
        chars(): $IntStream;
        array(): string[];
        mark(): $CharBuffer;
        read(arg0: $CharBuffer): number;
        flip(): $CharBuffer;
        slice(arg0: number, arg1: number): $CharBuffer;
        static allocate(arg0: number): $CharBuffer;
        asReadOnlyBuffer(): $CharBuffer;
        compact(): $CharBuffer;
        order(): $ByteOrder;
        codePoints(): $IntStream;
        append(arg0: $CharSequence): $Appendable;
        append(arg0: $CharSequence, arg1: number, arg2: number): $Appendable;
        append(arg0: $CharSequence): $Appendable;
        subSequence(arg0: number, arg1: number): $CharSequence;
        get empty(): boolean;
    }
    export class $ShortBuffer extends $Buffer implements $Comparable<$ShortBuffer> {
        get(): number;
        get(arg0: number, arg1: number[]): $ShortBuffer;
        get(arg0: number): number;
        get(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        get(arg0: number[]): $ShortBuffer;
        get(arg0: number, arg1: number[], arg2: number, arg3: number): $ShortBuffer;
        put(arg0: $ShortBuffer): $ShortBuffer;
        put(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        put(arg0: number[]): $ShortBuffer;
        put(arg0: number, arg1: $ShortBuffer, arg2: number, arg3: number): $ShortBuffer;
        put(arg0: number, arg1: number[]): $ShortBuffer;
        put(arg0: number, arg1: number[], arg2: number, arg3: number): $ShortBuffer;
        put(arg0: number, arg1: number): $ShortBuffer;
        put(arg0: number): $ShortBuffer;
        compareTo(arg0: $ShortBuffer): number;
        static wrap(arg0: number[]): $ShortBuffer;
        static wrap(arg0: number[], arg1: number, arg2: number): $ShortBuffer;
        mismatch(arg0: $ShortBuffer): number;
        limit(arg0: number): $ShortBuffer;
        array(): number[];
        flip(): $ShortBuffer;
        duplicate(): $ShortBuffer;
        static allocate(arg0: number): $ShortBuffer;
        asReadOnlyBuffer(): $ShortBuffer;
        compact(): $ShortBuffer;
        order(): $ByteOrder;
    }
}
