import { $Codec } from "@package/com/mojang/serialization";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $EntityType_, $EntityDimensions, $Entity$RemovalReason, $Pose, $PortalProcessor, $Entity, $EntityType$Builder } from "@package/net/minecraft/world/entity";
import { $ClientContraption } from "@package/com/simibubi/create/content/contraptions/render";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $CustomPacketPayload$Type, $CustomPacketPayload } from "@package/net/minecraft/network/protocol/common/custom";
import { $AccessorContraption, $AccessorOrientedContraptionEntity, $AccessorAbstractContraptionEntity } from "@package/com/railwayteam/railways/mixin";
import { $RandomSource } from "@package/net/minecraft/util";
import { $InteractionHand_ } from "@package/net/minecraft/world";
import { $BlockSnapshot } from "@package/net/neoforged/neoforge/common/util";
import { $MountedFluidStorage, $MountedFluidStorageWrapper } from "@package/com/simibubi/create/api/contraption/storage/fluid";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $FloatingClusterContainer } from "@package/dev/ryanhcode/sable/physics/floating_block";
import { $MountedStorageAccessor } from "@package/dev/ryanhcode/offroad/mixin";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $NeighborUpdater } from "@package/net/minecraft/world/level/redstone";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $IEntityWithComplexSpawn } from "@package/net/neoforged/neoforge/entity";
import { $Component } from "@package/net/minecraft/network/chat";
import { $ContraptionType } from "@package/com/simibubi/create/api/contraption";
import { $StructureTemplate$StructureBlockInfo_, $StructureTemplate$StructureBlockInfo } from "@package/net/minecraft/world/level/levelgen/structure/templatesystem";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $WritableLevelData } from "@package/net/minecraft/world/level/storage";
import { $MinecartController } from "@package/com/simibubi/create/content/contraptions/minecart/capability";
import { $CombinedInvWrapper } from "@package/net/neoforged/neoforge/items/wrapper";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $Mirror_, $Mirror, $Rotation_, $Rotation } from "@package/net/minecraft/world/level/block";
import { $MutableInt } from "@package/org/apache/commons/lang3/mutable";
import { $BasePacketPayload$PacketTypeProvider, $ClientboundPacketPayload } from "@package/net/createmod/catnip/net/base";
import { $Vec3, $AABB, $Vec3_ } from "@package/net/minecraft/world/phys";
import { $Vector3dc, $Quaterniond } from "@package/org/joml";
import { $KinematicContraption } from "@package/dev/ryanhcode/sable/api/sublevel";
import { $MassTracker } from "@package/dev/ryanhcode/sable/api/physics/mass";
import { $IFuelInventory, $IContraptionFuel } from "@package/com/railwayteam/railways/mixin_interfaces";
import { $MutablePair } from "@package/org/apache/commons/lang3/tuple";
import { $UUID_, $ArrayList, $Map, $UUID, $List, $Map_, $Collection_, $List_ } from "@package/java/util";
import { $ServerboundCustomPayloadPacket, $ClientboundCustomPayloadPacket } from "@package/net/minecraft/network/protocol/common";
import { $BiConsumer_ } from "@package/java/util/function";
import { $BlockPos, $Direction$Axis_, $BlockPos_, $Vec3i, $HolderLookup$Provider, $Direction_, $Direction$Axis, $Direction } from "@package/net/minecraft/core";
import { $Object2DoubleMap, $Object2BooleanMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $Iterable_, $Record } from "@package/java/lang";
import { $Couple } from "@package/net/createmod/catnip/data";
import { $CollisionList, $Matrix3d } from "@package/com/simibubi/create/foundation/collision";
import { $BlockGetter, $EntityGetter, $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $BoundingBox3i, $Pose3d } from "@package/dev/ryanhcode/sable/companion/math";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $LocalPlayer } from "@package/net/minecraft/client/player";
import { $IItemHandlerModifiable } from "@package/net/neoforged/neoforge/items";
import { $ImmutableMap } from "@package/com/google/common/collect";
import { $MovementBehaviour } from "@package/com/simibubi/create/api/behaviour/movement";
import { $MovingInteractionBehaviour } from "@package/com/simibubi/create/api/behaviour/interaction";
import { $EntityDataAccessor, $SynchedEntityData } from "@package/net/minecraft/network/syncher";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $WrappedLevel } from "@package/net/createmod/catnip/levelWrappers";
import { $MovementContext } from "@package/com/simibubi/create/content/contraptions/behaviour";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $MountedItemStorageWrapper, $MountedItemStorage } from "@package/com/simibubi/create/api/contraption/storage/item";
import { $ContraptionAccessor } from "@package/dev/simulated_team/simulated/mixin/accessor";
import { $BlockEntity, $TickingBlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $StreamCodec } from "@package/net/minecraft/network/codec";
export * as render from "@package/com/simibubi/create/content/contraptions/render";
export * as behaviour from "@package/com/simibubi/create/content/contraptions/behaviour";
export * as minecart from "@package/com/simibubi/create/content/contraptions/minecart";

declare module "@package/com/simibubi/create/content/contraptions" {
    export class $StructureTransform {
        apply(arg0: $BlockState_): $BlockState;
        apply(arg0: $BlockEntity): void;
        apply(arg0: $BlockPos_): $BlockPos;
        apply(arg0: $Vec3_): $Vec3;
        rotateFacing(arg0: $Direction_): $Direction;
        applyWithoutOffset(arg0: $BlockPos_): $BlockPos;
        applyWithoutOffset(arg0: $Vec3_): $Vec3;
        mirrorFacing(arg0: $Direction_): $Direction;
        applyWithoutOffsetUncentered(arg0: $Vec3_): $Vec3;
        unapplyWithoutOffset(arg0: $Vec3_): $Vec3;
        unapplyWithoutOffset(arg0: $BlockPos_): $BlockPos;
        unapply(arg0: $BlockPos_): $BlockPos;
        rotateAxis(arg0: $Direction$Axis_): $Direction$Axis;
        mirror: $Mirror;
        offset: $BlockPos;
        rotationAxis: $Direction$Axis;
        rotation: $Rotation;
        angle: number;
        static STREAM_CODEC: $StreamCodec<$ByteBuf, $StructureTransform>;
        constructor(arg0: $BlockPos_, arg1: number, arg2: number, arg3: number);
        constructor(arg0: $BlockPos_, arg1: $Direction$Axis_, arg2: $Rotation_, arg3: $Mirror_);
    }
    export class $AbstractContraptionEntity extends $Entity implements $IEntityWithComplexSpawn, $AccessorAbstractContraptionEntity, $KinematicContraption {
        static build(arg0: $EntityType$Builder<never>): $EntityType$Builder<never>;
        move(arg0: number, arg1: number, arg2: number): void;
        control(arg0: $BlockPos_, arg1: $Collection_<number>, arg2: $Player): boolean;
        toGlobalVector(arg0: $Vec3_, arg1: number): $Vec3;
        toGlobalVector(arg0: $Vec3_, arg1: number, arg2: boolean): $Vec3;
        getControllingPlayer(): ($UUID) | undefined;
        setControllingPlayer(arg0: $UUID_): void;
        addSittingPassenger(arg0: $Entity, arg1: number): void;
        handlePlayerInteraction(arg0: $Player, arg1: $BlockPos_, arg2: $Direction_, arg3: $InteractionHand_): boolean;
        startControlling(arg0: $BlockPos_, arg1: $Player): boolean;
        stopControlling(arg0: $BlockPos_): void;
        getPrevAnchorVec(): $Vec3;
        toLocalVector(arg0: $Vec3_, arg1: number, arg2: boolean): $Vec3;
        toLocalVector(arg0: $Vec3_, arg1: number): $Vec3;
        alignPassenger(arg0: $Entity): void;
        refreshPSIs(): void;
        getPrevPositionVec(): $Vec3;
        getYawOffset(): number;
        static yawFromVector(arg0: $Vec3_): number;
        static pitchFromVector(arg0: $Vec3_): number;
        writeSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        readSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        setContraptionMotion(arg0: $Vec3_): void;
        isReadyForRender(): boolean;
        isAliveOrStale(): boolean;
        isPrevPosInvalid(): boolean;
        sable$liftProviders(): $Map<any, any>;
        sable$blockGetter(): $BlockGetter;
        sable$getLocalBounds(arg0: $BoundingBox3i): void;
        sable$getMassTracker(): $MassTracker;
        sable$getPosition(arg0: number): $Vector3dc;
        sable$getOrientation(arg0: number): $Quaterniond;
        sable$isValid(): boolean;
        sable$shouldCollide(): boolean;
        sable$getFloatingClusterContainer(): $FloatingClusterContainer;
        isStalled(): boolean;
        reverseRotation(arg0: $Vec3_, arg1: number): $Vec3;
        getContactPointMotion(arg0: $Vec3_): $Vec3;
        getRotationState(): $AbstractContraptionEntity$ContraptionRotationState;
        tickActors(): void;
        getAnchorVec(): $Vec3;
        applyLocalTransforms(arg0: $PoseStack, arg1: number): void;
        supportsTerrainCollision(): boolean;
        collisionEnabled(): boolean;
        getPassengerPosition(arg0: $Entity, arg1: number): $Vec3;
        getContraptionName(): $Component;
        applyRotation(arg0: $Vec3_, arg1: number): $Vec3;
        disassemble(): void;
        setBlock(arg0: $BlockPos_, arg1: $StructureTemplate$StructureBlockInfo_): void;
        canInteractWithBlock(arg0: $Player, arg1: $Vec3_, arg2: number): boolean;
        canInteractWithBlock(arg0: $Player, arg1: $BlockPos_, arg2: number): boolean;
        getContraption(): $Contraption;
        registerColliding(arg0: $Entity): void;
        sable$getPosition(): $Vector3dc;
        sable$getOrientation(): $Quaterniond;
        sable$getLocalPose(arg0: $Pose3d, arg1: number): $Pose3d;
        railways$setSkipActorStop(arg0: boolean): void;
        railways$moveCollidedEntitiesOnDisassembly(arg0: $StructureTransform): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        staleTicks: number;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        collidingEntities: $Map<$Entity, $MutableInt>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<never>, arg1: $Level_);
        get prevAnchorVec(): $Vec3;
        get prevPositionVec(): $Vec3;
        get yawOffset(): number;
        set contraptionMotion(value: $Vec3_);
        get readyForRender(): boolean;
        get aliveOrStale(): boolean;
        get prevPosInvalid(): boolean;
        get stalled(): boolean;
        get rotationState(): $AbstractContraptionEntity$ContraptionRotationState;
        get anchorVec(): $Vec3;
        get contraptionName(): $Component;
        get contraption(): $Contraption;
    }
    export class $ContraptionWorld extends $WrappedLevel {
        self(): $EntityGetter;
        restoringBlockSnapshots: boolean;
        neighborUpdater: $NeighborUpdater;
        static LONG_PARTICLE_CLIP_RANGE: number;
        randValue: number;
        levelData: $WritableLevelData;
        thunderLevel: number;
        random: $RandomSource;
        capturedBlockSnapshots: $ArrayList<$BlockSnapshot>;
        static MAX_ENTITY_SPAWN_Y: number;
        static NETHER: $ResourceKey<$Level>;
        static MAX_BRIGHTNESS: number;
        static SHORT_PARTICLE_CLIP_RANGE: number;
        rainLevel: number;
        oThunderLevel: number;
        static ATTACHMENTS_NBT_KEY: string;
        addend: number;
        static OVERWORLD: $ResourceKey<$Level>;
        static TICKS_PER_DAY: number;
        oRainLevel: number;
        static RESOURCE_KEY_CODEC: $Codec<$ResourceKey<$Level>>;
        static END: $ResourceKey<$Level>;
        static MAX_LEVEL_SIZE: number;
        static MIN_ENTITY_SPAWN_Y: number;
        blockEntityTickers: $List<$TickingBlockEntity>;
        captureBlockSnapshots: boolean;
        constructor(arg0: $Level_, arg1: $Contraption);
    }
    export class $OrientedContraptionEntity extends $AbstractContraptionEntity implements $AccessorOrientedContraptionEntity {
        static create(arg0: $Level_, arg1: $Contraption, arg2: $Direction_): $OrientedContraptionEntity;
        setInitialOrientation(arg0: $Direction_): void;
        startAtInitialYaw(): void;
        static createAtYaw(arg0: $Level_, arg1: $Contraption, arg2: $Direction_, arg3: number): $OrientedContraptionEntity;
        startAtYaw(arg0: number): void;
        getInitialOrientation(): $Direction;
        getInitialYaw(): number;
        isInitialOrientationPresent(): boolean;
        setCouplingId(arg0: $UUID_): void;
        getCouplingId(): $UUID;
        getCoupledCartsIfPresent(): $Couple<$MinecartController>;
        static handleRelocationPacket(arg0: $ContraptionRelocationPacket_): void;
        railways$makeStructureTransform(): $StructureTransform;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        pitch: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        prevYaw: number;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        staleTicks: number;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        prevPitch: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        yaw: number;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        collidingEntities: $Map<$Entity, $MutableInt>;
        static BASE_SAFE_FALL_DISTANCE: number;
        nonDamageTicks: number;
        targetYaw: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<never>, arg1: $Level_);
        get initialYaw(): number;
        get initialOrientationPresent(): boolean;
        get coupledCartsIfPresent(): $Couple<$MinecartController>;
    }
    export class $Contraption implements $ContraptionAccessor, $AccessorContraption, $IContraptionFuel {
        stop(arg0: $Level_): void;
        getType(): $ContraptionType;
        startMoving(arg0: $Level_): void;
        static fromNBT(arg0: $Level_, arg1: $CompoundTag_, arg2: boolean): $Contraption;
        getActorAt(arg0: $BlockPos_): $MutablePair<$StructureTemplate$StructureBlockInfo, $MovementContext>;
        getBlockEntityClientSide(arg0: $BlockPos_): $BlockEntity;
        getDisabledActors(): $List<$ItemStack>;
        isActorTypeDisabled(arg0: $ItemStack_): boolean;
        setActorsActive(arg0: $ItemStack_, arg1: boolean): void;
        getSeatMapping(): $Map<$UUID, number>;
        getSeats(): $List<$BlockPos>;
        getActors(): $List<$MutablePair<$StructureTemplate$StructureBlockInfo, $MovementContext>>;
        invalidateClientContraptionChildren(): void;
        invalidateColliders(): void;
        addPassengersToWorld(arg0: $Level_, arg1: $StructureTransform, arg2: $List_<$Entity>): void;
        forEachActor(arg0: $Level_, arg1: $BiConsumer_<$MovementBehaviour, $MovementContext>): void;
        expandBoundsAroundAxis(arg0: $Direction$Axis_): void;
        getSeatOf(arg0: $UUID_): $BlockPos;
        getBearingPosOf(arg0: $UUID_): $BlockPos;
        setSeatMapping(arg0: $Map_<$UUID_, number>): void;
        getIsLegacy(): $Object2BooleanMap<$BlockPos>;
        getInteractors(): $Map<$BlockPos, $MovingInteractionBehaviour>;
        isHiddenInPortal(arg0: $BlockPos_): boolean;
        getSimplifiedEntityColliders(): $CollisionList;
        tickStorage(arg0: $AbstractContraptionEntity): void;
        getOrCreateClientContraptionLazy(): $ClientContraption;
        invalidateClientContraptionStructure(): void;
        railways$getFluidFuels(): $MountedFluidStorageWrapper;
        writeNBT(arg0: $HolderLookup$Provider, arg1: boolean): $CompoundTag;
        writeStorage(arg0: $CompoundTag_, arg1: $HolderLookup$Provider, arg2: boolean): void;
        resetClientContraption(): void;
        addBlocksToWorld(arg0: $Level_, arg1: $StructureTransform): void;
        removeBlocksFromWorld(arg0: $Level_, arg1: $BlockPos_): void;
        getContraptionWorld(): $ContraptionWorld;
        canBeStabilized(arg0: $Direction_, arg1: $BlockPos_): boolean;
        searchMovedStructure(arg0: $Level_, arg1: $BlockPos_, arg2: $Direction_): boolean;
        onEntityCreated(arg0: $AbstractContraptionEntity): void;
        onEntityInitialize(arg0: $Level_, arg1: $AbstractContraptionEntity): void;
        readNBT(arg0: $Level_, arg1: $CompoundTag_, arg2: boolean): void;
        containsBlockBreakers(): boolean;
        getStorage(): $MountedStorageManager;
        assemble(arg0: $Level_, arg1: $BlockPos_): boolean;
        static getRadius(arg0: $Iterable_<$Vec3i>, arg1: $Direction$Axis_): number;
        getBlocks(): $Map<$BlockPos, $StructureTemplate$StructureBlockInfo>;
        getSuperGlue(): $List<$AABB>;
        railways$getEntity(): $AbstractContraptionEntity;
        hasUniversalCreativeCrate: boolean;
        isLegacy: $Object2BooleanMap<$BlockPos>;
        anchor: $BlockPos;
        stalled: boolean;
        bounds: $AABB;
        simplifiedEntityColliders: $CollisionList;
        disassembled: boolean;
        entity: $AbstractContraptionEntity;
        constructor();
        get type(): $ContraptionType;
        get disabledActors(): $List<$ItemStack>;
        get seats(): $List<$BlockPos>;
        get actors(): $List<$MutablePair<$StructureTemplate$StructureBlockInfo, $MovementContext>>;
        get interactors(): $Map<$BlockPos, $MovingInteractionBehaviour>;
        get orCreateClientContraptionLazy(): $ClientContraption;
        get contraptionWorld(): $ContraptionWorld;
        get storage(): $MountedStorageManager;
        get blocks(): $Map<$BlockPos, $StructureTemplate$StructureBlockInfo>;
        get superGlue(): $List<$AABB>;
    }
    export class $AbstractContraptionEntity$ContraptionRotationState {
        getYawOffset(): number;
        asMatrix(): $Matrix3d;
        hasVerticalRotation(): boolean;
        xRotation: number;
        secondYRotation: number;
        zRotation: number;
        static NONE: $AbstractContraptionEntity$ContraptionRotationState;
        yRotation: number;
        constructor();
        get yawOffset(): number;
    }
    export class $MountedStorageManager implements $MountedStorageAccessor, $IFuelInventory {
        initialize(): void;
        unmount(arg0: $Level_, arg1: $StructureTemplate$StructureBlockInfo_, arg2: $BlockPos_, arg3: $BlockEntity): void;
        write(arg0: $CompoundTag_, arg1: $HolderLookup$Provider, arg2: boolean): void;
        read(arg0: $CompoundTag_, arg1: $HolderLookup$Provider, arg2: boolean, arg3: $Contraption): void;
        tick(arg0: $AbstractContraptionEntity): void;
        getAllItemStorages(): $ImmutableMap<$BlockPos, $MountedItemStorage>;
        getFluids(): $MountedFluidStorageWrapper;
        attachExternal(arg0: $IItemHandlerModifiable): void;
        railways$getFluidFuels(): $MountedFluidStorageWrapper;
        getMountedItems(): $MountedItemStorageWrapper;
        handlePlayerStorageInteraction(arg0: $Contraption, arg1: $Player, arg2: $BlockPos_): boolean;
        getFuelItems(): $MountedItemStorageWrapper;
        getAllItems(): $CombinedInvWrapper;
        addBlock(arg0: $Level_, arg1: $BlockState_, arg2: $BlockPos_, arg3: $BlockPos_, arg4: $BlockEntity): void;
        handleSync(arg0: $MountedStorageSyncPacket_, arg1: $AbstractContraptionEntity): void;
        getItemsBuilder(): $Map<$BlockPos, $MountedItemStorage>;
        constructor();
        get allItemStorages(): $ImmutableMap<$BlockPos, $MountedItemStorage>;
        get fluids(): $MountedFluidStorageWrapper;
        get mountedItems(): $MountedItemStorageWrapper;
        get fuelItems(): $MountedItemStorageWrapper;
        get allItems(): $CombinedInvWrapper;
        get itemsBuilder(): $Map<$BlockPos, $MountedItemStorage>;
    }
    export class $MountedStorageSyncPacket extends $Record implements $ClientboundPacketPayload {
        handle(arg0: $LocalPlayer): void;
        contraptionId(): number;
        getTypeProvider(): $BasePacketPayload$PacketTypeProvider;
        items(): $Map<$BlockPos, $MountedItemStorage>;
        fluids(): $Map<$BlockPos, $MountedFluidStorage>;
        handleInternal(arg0: $Player): void;
        type(): $CustomPacketPayload$Type<$CustomPacketPayload>;
        toVanillaClientbound(): $ClientboundCustomPayloadPacket;
        toVanillaServerbound(): $ServerboundCustomPayloadPacket;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $MountedStorageSyncPacket>;
        constructor(contraptionId: number, items: $Map_<$BlockPos_, $MountedItemStorage>, fluids: $Map_<$BlockPos_, $MountedFluidStorage>);
        get typeProvider(): $BasePacketPayload$PacketTypeProvider;
    }
    /**
     * Values that may be interpreted as {@link $MountedStorageSyncPacket}.
     */
    export type $MountedStorageSyncPacket_ = { fluids?: $Map_<$BlockPos_, $MountedFluidStorage>, items?: $Map_<$BlockPos_, $MountedItemStorage>, contraptionId?: number,  } | [fluids?: $Map_<$BlockPos_, $MountedFluidStorage>, items?: $Map_<$BlockPos_, $MountedItemStorage>, contraptionId?: number, ];
}
