import { $AttributedCharacterIterator$Attribute } from "@package/java/text";
import { $Point2D, $Rectangle2D, $AffineTransform } from "@package/java/awt/geom";
import { $Font, $Shape, $Rectangle } from "@package/java/awt";
import { $Object, $Cloneable } from "@package/java/lang";

declare module "@package/java/awt/font" {
    export class $FontRenderContext {
        isAntiAliased(): boolean;
        usesFractionalMetrics(): boolean;
        getAntiAliasingHint(): $Object;
        getFractionalMetricsHint(): $Object;
        getTransformType(): number;
        getTransform(): $AffineTransform;
        equals(arg0: $FontRenderContext): boolean;
        isTransformed(): boolean;
        constructor(arg0: $AffineTransform, arg1: boolean, arg2: boolean);
        constructor(arg0: $AffineTransform, arg1: $Object, arg2: $Object);
        get antiAliased(): boolean;
        get antiAliasingHint(): $Object;
        get fractionalMetricsHint(): $Object;
        get transformType(): number;
        get transform(): $AffineTransform;
        get transformed(): boolean;
    }
    export class $TextHitInfo {
        getInsertionIndex(): number;
        static trailing(arg0: number): $TextHitInfo;
        isLeadingEdge(): boolean;
        static beforeOffset(arg0: number): $TextHitInfo;
        static afterOffset(arg0: number): $TextHitInfo;
        getOtherHit(): $TextHitInfo;
        getOffsetHit(arg0: number): $TextHitInfo;
        equals(arg0: $TextHitInfo): boolean;
        getCharIndex(): number;
        static leading(arg0: number): $TextHitInfo;
        get insertionIndex(): number;
        get leadingEdge(): boolean;
        get otherHit(): $TextHitInfo;
        get charIndex(): number;
    }
    export class $GlyphVector implements $Cloneable {
        getNumGlyphs(): number;
        getGlyphOutline(arg0: number): $Shape;
        getGlyphOutline(arg0: number, arg1: number, arg2: number): $Shape;
        getFontRenderContext(): $FontRenderContext;
        getOutline(): $Shape;
        getOutline(arg0: number, arg1: number): $Shape;
        getGlyphMetrics(arg0: number): $GlyphMetrics;
        getGlyphCode(arg0: number): number;
        getLayoutFlags(): number;
        getGlyphVisualBounds(arg0: number): $Shape;
        getGlyphTransform(arg0: number): $AffineTransform;
        setGlyphTransform(arg0: number, arg1: $AffineTransform): void;
        getGlyphPosition(arg0: number): $Point2D;
        getGlyphCodes(arg0: number, arg1: number, arg2: number[]): number[];
        getGlyphPositions(arg0: number, arg1: number, arg2: number[]): number[];
        getGlyphCharIndices(arg0: number, arg1: number, arg2: number[]): number[];
        performDefaultLayout(): void;
        getGlyphCharIndex(arg0: number): number;
        getLogicalBounds(): $Rectangle2D;
        getVisualBounds(): $Rectangle2D;
        getPixelBounds(arg0: $FontRenderContext, arg1: number, arg2: number): $Rectangle;
        setGlyphPosition(arg0: number, arg1: $Point2D): void;
        getGlyphLogicalBounds(arg0: number): $Shape;
        getGlyphPixelBounds(arg0: number, arg1: $FontRenderContext, arg2: number, arg3: number): $Rectangle;
        getGlyphJustificationInfo(arg0: number): $GlyphJustificationInfo;
        equals(arg0: $GlyphVector): boolean;
        getFont(): $Font;
        static FLAG_HAS_TRANSFORMS: number;
        static FLAG_HAS_POSITION_ADJUSTMENTS: number;
        static FLAG_MASK: number;
        static FLAG_COMPLEX_GLYPHS: number;
        static FLAG_RUN_RTL: number;
        get numGlyphs(): number;
        get fontRenderContext(): $FontRenderContext;
        get layoutFlags(): number;
        get logicalBounds(): $Rectangle2D;
        get visualBounds(): $Rectangle2D;
        get font(): $Font;
    }
    export class $GlyphJustificationInfo {
        growRightLimit: number;
        static PRIORITY_WHITESPACE: number;
        shrinkLeftLimit: number;
        weight: number;
        shrinkRightLimit: number;
        shrinkAbsorb: boolean;
        growPriority: number;
        static PRIORITY_KASHIDA: number;
        growAbsorb: boolean;
        static PRIORITY_NONE: number;
        growLeftLimit: number;
        static PRIORITY_INTERCHAR: number;
        shrinkPriority: number;
        constructor(arg0: number, arg1: boolean, arg2: number, arg3: number, arg4: number, arg5: boolean, arg6: number, arg7: number, arg8: number);
    }
    export class $TextAttribute extends $AttributedCharacterIterator$Attribute {
        static WEIGHT_BOLD: number;
        static UNDERLINE_LOW_GRAY: number;
        static NUMERIC_SHAPING: $TextAttribute;
        static WIDTH_SEMI_CONDENSED: number;
        static WIDTH_REGULAR: number;
        static SWAP_COLORS: $TextAttribute;
        static WIDTH_SEMI_EXTENDED: number;
        static RUN_DIRECTION: $TextAttribute;
        static WIDTH_EXTENDED: number;
        static CHAR_REPLACEMENT: $TextAttribute;
        static BIDI_EMBEDDING: $TextAttribute;
        static UNDERLINE_LOW_DASHED: number;
        static INPUT_METHOD_HIGHLIGHT: $TextAttribute;
        static STRIKETHROUGH_ON: boolean;
        static TRANSFORM: $TextAttribute;
        static WEIGHT: $TextAttribute;
        static SWAP_COLORS_ON: boolean;
        static JUSTIFICATION_FULL: number;
        static LANGUAGE: $AttributedCharacterIterator$Attribute;
        static WEIGHT_HEAVY: number;
        static SIZE: $TextAttribute;
        static POSTURE_REGULAR: number;
        static KERNING_ON: number;
        static BACKGROUND: $TextAttribute;
        static RUN_DIRECTION_LTR: boolean;
        static RUN_DIRECTION_RTL: boolean;
        static WIDTH_CONDENSED: number;
        static LIGATURES_ON: number;
        static SUPERSCRIPT: $TextAttribute;
        static JUSTIFICATION: $TextAttribute;
        static KERNING: $TextAttribute;
        static WEIGHT_SEMIBOLD: number;
        static INPUT_METHOD_SEGMENT: $AttributedCharacterIterator$Attribute;
        static LIGATURES: $TextAttribute;
        static WEIGHT_DEMILIGHT: number;
        static WEIGHT_ULTRABOLD: number;
        static JUSTIFICATION_NONE: number;
        static UNDERLINE_LOW_ONE_PIXEL: number;
        static UNDERLINE_ON: number;
        static POSTURE_OBLIQUE: number;
        static WEIGHT_REGULAR: number;
        static WIDTH: $TextAttribute;
        static SUPERSCRIPT_SUPER: number;
        static UNDERLINE: $TextAttribute;
        static FAMILY: $TextAttribute;
        static WEIGHT_LIGHT: number;
        static POSTURE: $TextAttribute;
        static TRACKING_LOOSE: number;
        static WEIGHT_EXTRA_LIGHT: number;
        static TRACKING: $TextAttribute;
        static READING: $AttributedCharacterIterator$Attribute;
        static INPUT_METHOD_UNDERLINE: $TextAttribute;
        static TRACKING_TIGHT: number;
        static UNDERLINE_LOW_DOTTED: number;
        static SUPERSCRIPT_SUB: number;
        static FONT: $TextAttribute;
        static FOREGROUND: $TextAttribute;
        static STRIKETHROUGH: $TextAttribute;
        static WEIGHT_DEMIBOLD: number;
        static WEIGHT_EXTRABOLD: number;
        static WEIGHT_MEDIUM: number;
        static UNDERLINE_LOW_TWO_PIXEL: number;
    }
    export class $LineMetrics {
        getLeading(): number;
        getAscent(): number;
        getDescent(): number;
        getUnderlineOffset(): number;
        getUnderlineThickness(): number;
        getStrikethroughOffset(): number;
        getStrikethroughThickness(): number;
        getNumChars(): number;
        getBaselineIndex(): number;
        getBaselineOffsets(): number[];
        getHeight(): number;
        get leading(): number;
        get ascent(): number;
        get descent(): number;
        get underlineOffset(): number;
        get underlineThickness(): number;
        get strikethroughOffset(): number;
        get strikethroughThickness(): number;
        get numChars(): number;
        get baselineIndex(): number;
        get baselineOffsets(): number[];
        get height(): number;
    }
    export class $GlyphMetrics {
        getBounds2D(): $Rectangle2D;
        getAdvanceX(): number;
        getAdvance(): number;
        getAdvanceY(): number;
        getLSB(): number;
        getRSB(): number;
        isLigature(): boolean;
        isCombining(): boolean;
        isComponent(): boolean;
        isStandard(): boolean;
        isWhitespace(): boolean;
        getType(): number;
        static COMBINING: number;
        static WHITESPACE: number;
        static LIGATURE: number;
        static COMPONENT: number;
        static STANDARD: number;
        constructor(arg0: boolean, arg1: number, arg2: number, arg3: $Rectangle2D, arg4: number);
        constructor(arg0: number, arg1: $Rectangle2D, arg2: number);
        get bounds2D(): $Rectangle2D;
        get advanceX(): number;
        get advance(): number;
        get advanceY(): number;
        get LSB(): number;
        get RSB(): number;
        get ligature(): boolean;
        get combining(): boolean;
        get component(): boolean;
        get standard(): boolean;
        get whitespace(): boolean;
        get type(): number;
    }
}
