import { $InputStream, $OutputStream } from "@package/java/io";
import { $ReferenceCounted, $ByteProcessor_ } from "@package/io/netty/util";
import { $Consumer_ } from "@package/java/util/function";
import { $Charset } from "@package/java/nio/charset";
import { $Spliterator, $Iterator, $List } from "@package/java/util";
import { $CharSequence, $Iterable_, $Comparable, $Object, $Iterable } from "@package/java/lang";
import { $ScatteringByteChannel, $GatheringByteChannel, $FileChannel } from "@package/java/nio/channels";
import { $ByteBuffer, $ByteOrder } from "@package/java/nio";

declare module "@package/io/netty/buffer" {
    export class $ByteBufConvertible {
    }
    export interface $ByteBufConvertible {
        asByteBuf(): $ByteBuf;
    }
    /**
     * Values that may be interpreted as {@link $ByteBufConvertible}.
     */
    export type $ByteBufConvertible_ = (() => $ByteBuf);
    export class $AbstractByteBuf extends $ByteBuf {
    }
    export class $CompositeByteBuf extends $AbstractReferenceCountedByteBuf implements $Iterable<$ByteBuf> {
        getBytes(arg0: number, arg1: $OutputStream, arg2: number): $CompositeByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf): $CompositeByteBuf;
        getBytes(arg0: number, arg1: number[]): $CompositeByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number): $CompositeByteBuf;
        getBytes(arg0: number, arg1: number[], arg2: number, arg3: number): $CompositeByteBuf;
        getBytes(arg0: number, arg1: $ByteBuffer): $CompositeByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number, arg3: number): $CompositeByteBuf;
        iterator(): $Iterator<$ByteBuf>;
        component(arg0: number): $ByteBuf;
        setByte(arg0: number, arg1: number): $CompositeByteBuf;
        setLong(arg0: number, arg1: number): $CompositeByteBuf;
        capacity(arg0: number): $CompositeByteBuf;
        writeLong(arg0: number): $CompositeByteBuf;
        writeByte(arg0: number): $CompositeByteBuf;
        writeShort(arg0: number): $CompositeByteBuf;
        readBytes(arg0: $ByteBuffer): $CompositeByteBuf;
        readBytes(arg0: $OutputStream, arg1: number): $CompositeByteBuf;
        readBytes(arg0: $ByteBuf): $CompositeByteBuf;
        writeBytes(arg0: $ByteBuf): $CompositeByteBuf;
        writeBytes(arg0: number[]): $CompositeByteBuf;
        writeBytes(arg0: number[], arg1: number, arg2: number): $CompositeByteBuf;
        writeFloat(arg0: number): $CompositeByteBuf;
        writeDouble(arg0: number): $CompositeByteBuf;
        writeBoolean(arg0: boolean): $CompositeByteBuf;
        maxNumComponents(): number;
        addFlattenedComponents(arg0: boolean, arg1: $ByteBuf): $CompositeByteBuf;
        numComponents(): number;
        removeComponent(arg0: number): $CompositeByteBuf;
        removeComponents(arg0: number, arg1: number): $CompositeByteBuf;
        toComponentIndex(arg0: number): number;
        toByteIndex(arg0: number): number;
        addComponents(arg0: $Iterable_<$ByteBuf>): $CompositeByteBuf;
        addComponents(...arg0: $ByteBuf[]): $CompositeByteBuf;
        addComponents(arg0: number, arg1: $Iterable_<$ByteBuf>): $CompositeByteBuf;
        addComponents(arg0: number, ...arg1: $ByteBuf[]): $CompositeByteBuf;
        addComponents(arg0: boolean, arg1: $Iterable_<$ByteBuf>): $CompositeByteBuf;
        addComponents(arg0: boolean, ...arg1: $ByteBuf[]): $CompositeByteBuf;
        componentAtOffset(arg0: number): $ByteBuf;
        internalComponent(arg0: number): $ByteBuf;
        internalComponentAtOffset(arg0: number): $ByteBuf;
        discardReadComponents(): $CompositeByteBuf;
        readerIndex(arg0: number): $CompositeByteBuf;
        markReaderIndex(): $CompositeByteBuf;
        resetReaderIndex(): $CompositeByteBuf;
        markWriterIndex(): $CompositeByteBuf;
        discardReadBytes(): $CompositeByteBuf;
        discardSomeReadBytes(): $CompositeByteBuf;
        setZero(arg0: number, arg1: number): $CompositeByteBuf;
        writeZero(arg0: number): $CompositeByteBuf;
        decompose(arg0: number, arg1: number): $List<$ByteBuf>;
        addComponent(arg0: $ByteBuf): $CompositeByteBuf;
        addComponent(arg0: boolean, arg1: $ByteBuf): $CompositeByteBuf;
        addComponent(arg0: number, arg1: $ByteBuf): $CompositeByteBuf;
        addComponent(arg0: boolean, arg1: number, arg2: $ByteBuf): $CompositeByteBuf;
        consolidate(): $CompositeByteBuf;
        consolidate(arg0: number, arg1: number): $CompositeByteBuf;
        spliterator(): $Spliterator<$ByteBuf>;
        forEach(arg0: $Consumer_<$ByteBuf>): void;
        retain(): $ByteBuf;
        retain(arg0: number): $ByteBuf;
        touch(arg0: $Object): $ByteBuf;
        constructor(arg0: $ByteBufAllocator, arg1: boolean, arg2: number, arg3: $Iterable_<$ByteBuf>);
        constructor(arg0: $ByteBufAllocator, arg1: boolean, arg2: number);
        constructor(arg0: $ByteBufAllocator, arg1: boolean, arg2: number, ...arg3: $ByteBuf[]);
        [Symbol.iterator](): Iterator<$ByteBuf>
    }
    export class $ByteBuf implements $ReferenceCounted, $Comparable<$ByteBuf>, $ByteBufConvertible {
        toString(arg0: number, arg1: number, arg2: $Charset): string;
        toString(arg0: $Charset): string;
        compareTo(arg0: $ByteBuf): number;
        indexOf(arg0: number, arg1: number, arg2: number): number;
        getBoolean(arg0: number): boolean;
        getByte(arg0: number): number;
        getShort(arg0: number): number;
        getChar(arg0: number): string;
        getInt(arg0: number): number;
        getLong(arg0: number): number;
        getFloat(arg0: number): number;
        getDouble(arg0: number): number;
        clear(): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuffer): $ByteBuf;
        getBytes(arg0: number, arg1: $OutputStream, arg2: number): $ByteBuf;
        getBytes(arg0: number, arg1: $GatheringByteChannel, arg2: number): number;
        getBytes(arg0: number, arg1: $FileChannel, arg2: number, arg3: number): number;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number, arg3: number): $ByteBuf;
        getBytes(arg0: number, arg1: number[]): $ByteBuf;
        getBytes(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuf;
        copy(arg0: number, arg1: number): $ByteBuf;
        copy(): $ByteBuf;
        isDirect(): boolean;
        hasArray(): boolean;
        array(): number[];
        arrayOffset(): number;
        writeInt(arg0: number): $ByteBuf;
        readInt(): number;
        setBoolean(arg0: number, arg1: boolean): $ByteBuf;
        setByte(arg0: number, arg1: number): $ByteBuf;
        setChar(arg0: number, arg1: number): $ByteBuf;
        setShort(arg0: number, arg1: number): $ByteBuf;
        setInt(arg0: number, arg1: number): $ByteBuf;
        setLong(arg0: number, arg1: number): $ByteBuf;
        setFloat(arg0: number, arg1: number): $ByteBuf;
        setDouble(arg0: number, arg1: number): $ByteBuf;
        unwrap(): $ByteBuf;
        capacity(): number;
        capacity(arg0: number): $ByteBuf;
        isReadOnly(): boolean;
        slice(arg0: number, arg1: number): $ByteBuf;
        slice(): $ByteBuf;
        duplicate(): $ByteBuf;
        readLong(): number;
        readByte(): number;
        readShort(): number;
        writeLong(arg0: number): $ByteBuf;
        writeByte(arg0: number): $ByteBuf;
        writeShort(arg0: number): $ByteBuf;
        readBytes(arg0: number[], arg1: number, arg2: number): $ByteBuf;
        readBytes(arg0: $ByteBuf, arg1: number, arg2: number): $ByteBuf;
        readBytes(arg0: $ByteBuf, arg1: number): $ByteBuf;
        readBytes(arg0: number[]): $ByteBuf;
        readBytes(arg0: $FileChannel, arg1: number, arg2: number): number;
        readBytes(arg0: $OutputStream, arg1: number): $ByteBuf;
        readBytes(arg0: $GatheringByteChannel, arg1: number): number;
        readBytes(arg0: number): $ByteBuf;
        readBytes(arg0: $ByteBuffer): $ByteBuf;
        readBytes(arg0: $ByteBuf): $ByteBuf;
        writeBytes(arg0: $ScatteringByteChannel, arg1: number): number;
        writeBytes(arg0: number[]): $ByteBuf;
        writeBytes(arg0: number[], arg1: number, arg2: number): $ByteBuf;
        writeBytes(arg0: $ByteBuffer): $ByteBuf;
        writeBytes(arg0: $InputStream, arg1: number): number;
        writeBytes(arg0: $FileChannel, arg1: number, arg2: number): number;
        writeBytes(arg0: $ByteBuf): $ByteBuf;
        writeBytes(arg0: $ByteBuf, arg1: number): $ByteBuf;
        writeBytes(arg0: $ByteBuf, arg1: number, arg2: number): $ByteBuf;
        /**
         * @deprecated
         */
        order(): $ByteOrder;
        /**
         * @deprecated
         */
        order(arg0: $ByteOrder): $ByteBuf;
        isWritable(): boolean;
        isWritable(arg0: number): boolean;
        readUnsignedShort(): number;
        writeChar(arg0: number): $ByteBuf;
        readChar(): string;
        writeFloat(arg0: number): $ByteBuf;
        readFloat(): number;
        writeDouble(arg0: number): $ByteBuf;
        readDouble(): number;
        skipBytes(arg0: number): $ByteBuf;
        readBoolean(): boolean;
        readUnsignedByte(): number;
        getUnsignedShort(arg0: number): number;
        writeBoolean(arg0: boolean): $ByteBuf;
        isReadable(): boolean;
        isReadable(arg0: number): boolean;
        setIndex(arg0: number, arg1: number): $ByteBuf;
        alloc(): $ByteBufAllocator;
        readerIndex(): number;
        readerIndex(arg0: number): $ByteBuf;
        writerIndex(): number;
        writerIndex(arg0: number): $ByteBuf;
        readableBytes(): number;
        writableBytes(): number;
        maxWritableBytes(): number;
        maxFastWritableBytes(): number;
        markReaderIndex(): $ByteBuf;
        resetReaderIndex(): $ByteBuf;
        markWriterIndex(): $ByteBuf;
        resetWriterIndex(): $ByteBuf;
        discardReadBytes(): $ByteBuf;
        discardSomeReadBytes(): $ByteBuf;
        ensureWritable(arg0: number): $ByteBuf;
        ensureWritable(arg0: number, arg1: boolean): number;
        getUnsignedByte(arg0: number): number;
        getShortLE(arg0: number): number;
        getUnsignedShortLE(arg0: number): number;
        getMedium(arg0: number): number;
        getMediumLE(arg0: number): number;
        getUnsignedMedium(arg0: number): number;
        getUnsignedMediumLE(arg0: number): number;
        getIntLE(arg0: number): number;
        getUnsignedInt(arg0: number): number;
        getUnsignedIntLE(arg0: number): number;
        getLongLE(arg0: number): number;
        getFloatLE(arg0: number): number;
        getDoubleLE(arg0: number): number;
        setShortLE(arg0: number, arg1: number): $ByteBuf;
        setMedium(arg0: number, arg1: number): $ByteBuf;
        setMediumLE(arg0: number, arg1: number): $ByteBuf;
        setIntLE(arg0: number, arg1: number): $ByteBuf;
        setLongLE(arg0: number, arg1: number): $ByteBuf;
        setFloatLE(arg0: number, arg1: number): $ByteBuf;
        setDoubleLE(arg0: number, arg1: number): $ByteBuf;
        setBytes(arg0: number, arg1: number[]): $ByteBuf;
        setBytes(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuf;
        setBytes(arg0: number, arg1: $InputStream, arg2: number): number;
        setBytes(arg0: number, arg1: $ByteBuf, arg2: number, arg3: number): $ByteBuf;
        setBytes(arg0: number, arg1: $ByteBuf, arg2: number): $ByteBuf;
        setBytes(arg0: number, arg1: $ByteBuf): $ByteBuf;
        setBytes(arg0: number, arg1: $ByteBuffer): $ByteBuf;
        setBytes(arg0: number, arg1: $ScatteringByteChannel, arg2: number): number;
        setBytes(arg0: number, arg1: $FileChannel, arg2: number, arg3: number): number;
        setZero(arg0: number, arg1: number): $ByteBuf;
        setCharSequence(arg0: number, arg1: $CharSequence, arg2: $Charset): number;
        readShortLE(): number;
        readUnsignedShortLE(): number;
        readMedium(): number;
        readMediumLE(): number;
        readUnsignedMedium(): number;
        readUnsignedMediumLE(): number;
        readIntLE(): number;
        readUnsignedInt(): number;
        readUnsignedIntLE(): number;
        readLongLE(): number;
        readFloatLE(): number;
        readDoubleLE(): number;
        readSlice(arg0: number): $ByteBuf;
        readRetainedSlice(arg0: number): $ByteBuf;
        readCharSequence(arg0: number, arg1: $Charset): $CharSequence;
        writeShortLE(arg0: number): $ByteBuf;
        writeMedium(arg0: number): $ByteBuf;
        writeMediumLE(arg0: number): $ByteBuf;
        writeIntLE(arg0: number): $ByteBuf;
        writeLongLE(arg0: number): $ByteBuf;
        writeFloatLE(arg0: number): $ByteBuf;
        writeDoubleLE(arg0: number): $ByteBuf;
        writeZero(arg0: number): $ByteBuf;
        writeCharSequence(arg0: $CharSequence, arg1: $Charset): number;
        bytesBefore(arg0: number): number;
        bytesBefore(arg0: number, arg1: number): number;
        bytesBefore(arg0: number, arg1: number, arg2: number): number;
        retainedSlice(): $ByteBuf;
        retainedSlice(arg0: number, arg1: number): $ByteBuf;
        retainedDuplicate(): $ByteBuf;
        nioBufferCount(): number;
        nioBuffer(arg0: number, arg1: number): $ByteBuffer;
        nioBuffer(): $ByteBuffer;
        internalNioBuffer(arg0: number, arg1: number): $ByteBuffer;
        nioBuffers(): $ByteBuffer[];
        nioBuffers(arg0: number, arg1: number): $ByteBuffer[];
        hasMemoryAddress(): boolean;
        isContiguous(): boolean;
        asByteBuf(): $ByteBuf;
        retain(arg0: number): $ByteBuf;
        retain(): $ByteBuf;
        memoryAddress(): number;
        maxCapacity(): number;
        touch(): $ByteBuf;
        touch(arg0: $Object): $ByteBuf;
        asReadOnly(): $ByteBuf;
        getCharSequence(arg0: number, arg1: number, arg2: $Charset): $CharSequence;
        forEachByte(arg0: number, arg1: number, arg2: $ByteProcessor_): number;
        forEachByte(arg0: $ByteProcessor_): number;
        forEachByteDesc(arg0: number, arg1: number, arg2: $ByteProcessor_): number;
        forEachByteDesc(arg0: $ByteProcessor_): number;
        constructor();
        get direct(): boolean;
        get readOnly(): boolean;
        get contiguous(): boolean;
    }
    export class $AbstractReferenceCountedByteBuf extends $AbstractByteBuf {
        retain(): $ByteBuf;
        retain(arg0: number): $ByteBuf;
    }
    export class $ByteBufAllocator {
        static DEFAULT: $ByteBufAllocator;
    }
    export interface $ByteBufAllocator {
        buffer(): $ByteBuf;
        buffer(arg0: number, arg1: number): $ByteBuf;
        buffer(arg0: number): $ByteBuf;
        directBuffer(): $ByteBuf;
        directBuffer(arg0: number): $ByteBuf;
        directBuffer(arg0: number, arg1: number): $ByteBuf;
        heapBuffer(arg0: number): $ByteBuf;
        heapBuffer(arg0: number, arg1: number): $ByteBuf;
        heapBuffer(): $ByteBuf;
        ioBuffer(): $ByteBuf;
        ioBuffer(arg0: number, arg1: number): $ByteBuf;
        ioBuffer(arg0: number): $ByteBuf;
        compositeHeapBuffer(): $CompositeByteBuf;
        compositeHeapBuffer(arg0: number): $CompositeByteBuf;
        compositeDirectBuffer(arg0: number): $CompositeByteBuf;
        compositeDirectBuffer(): $CompositeByteBuf;
        isDirectBufferPooled(): boolean;
        calculateNewCapacity(arg0: number, arg1: number): number;
        compositeBuffer(): $CompositeByteBuf;
        compositeBuffer(arg0: number): $CompositeByteBuf;
        get directBufferPooled(): boolean;
    }
}
