import { $MoreJSBinding } from "@package/com/almostreliable/morejs";
import { $JEIUIEvents } from "@package/com/lowdragmc/lowdraglib2/integration/xei/jei";
import { $XmlUtils } from "@package/com/lowdragmc/lowdraglib2/utils";
import { $EntityIngredientWrapper, $CastingOutputWrapper } from "@package/fr/lucreeper74/createmetallurgy/compat/kubejs/recipe";
import { $RectTexture, $ColorRectTexture, $ColorBorderTexture, $AnimationTexture, $IGuiTexture, $SpriteTexture, $UIResourceTexture, $FluidStackTexture, $DynamicTexture, $ShaderTexture, $VanillaSpriteTexture, $TextTexture, $GuiTextureGroup, $SDFRectTexture, $ItemStackTexture } from "@package/com/lowdragmc/lowdraglib2/gui/texture";
import { $Minecraft } from "@package/net/minecraft/client";
import { $Stylesheet, $StylesheetManager } from "@package/com/lowdragmc/lowdraglib2/gui/ui/style";
import { $AbstractMap } from "@package/java/util";
import { $Position, $Size } from "@package/com/lowdragmc/lowdraglib2/math";
import { $BlockPos, $Vec3i } from "@package/net/minecraft/core";
import { $InventorySlots } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements/inventory";
import { $CodeEditor } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements/codeeditor";
import { $RotationAxis, $NBTIOWrapper, $MobEffectUtil, $JsonUtils, $NotificationToastData, $JsonIO, $ID, $FluidAmounts } from "@package/dev/latvian/mods/kubejs/util";
import { $EnchantmentInstance } from "@package/net/minecraft/world/item/enchantment";
import { $UI, $ModularUI, $UIElement } from "@package/com/lowdragmc/lowdraglib2/gui/ui";
import { $UIEvents, $UIEventListener, $HoverTooltips, $UIEventDispatcher } from "@package/com/lowdragmc/lowdraglib2/gui/ui/event";
import { $Math } from "@package/java/lang";
import { $TexturesResource, $UIResource, $IRendererResource, $ColorsResource } from "@package/com/lowdragmc/lowdraglib2/editor/resource";
import { $ConsoleJS, $PlatformWrapper } from "@package/dev/latvian/mods/kubejs/script";
import { $COEUtil } from "@package/com/tom/createores/kubejs";
import { $DeferredHolder } from "@package/net/neoforged/neoforge/registries";
import { $BlockStatePredicate } from "@package/dev/latvian/mods/kubejs/block/state";
import { $Items } from "@package/net/minecraft/world/item";
import { $LocalSlot, $ItemHandlerSlot } from "@package/com/lowdragmc/lowdraglib2/gui/slot";
import { $FluidWrapper } from "@package/dev/latvian/mods/kubejs/fluid";
import { $KubeCreateOutput } from "@package/dev/latvian/mods/kubejs/create/wrapper";
import { $TreeBuilder, $TreeBuilder$Menu } from "@package/com/lowdragmc/lowdraglib2/gui/util";
import { $ClipboardManager } from "@package/com/lowdragmc/lowdraglib2/editor";
import { $KMath, $TextWrapper, $IngredientWrapper, $SizedIngredientWrapper, $UUIDWrapper, $ParticleOptionsWrapper, $RegistryWrapper, $EntitySelectorWrapper, $NBTWrapper, $BlockWrapper, $DirectionWrapper, $NativeEventWrapper, $JavaWrapper, $UtilsWrapper, $TextIcons, $ColorWrapper, $AABBWrapper, $StringUtilsWrapper, $ItemWrapper, $DataMapWrapper } from "@package/dev/latvian/mods/kubejs/plugin/builtin/wrapper";
import { $ProcessingOutput } from "@package/com/simibubi/create/content/processing/recipe";
import { $ScrollDataSource, $DataBindingBuilder, $SupplierDataSource } from "@package/com/lowdragmc/lowdraglib2/gui/sync/bindings/impl";
import { $Switch, $Selector, $UITemplateElement, $ScrollerView, $Menu, $SplitView$Horizontal, $Label, $TreeList, $ProgressBar, $ColorSelector, $Inspector, $Scroller$Horizontal, $TextField, $TagField, $Tab, $Scroller$Vertical, $SplitView$Vertical, $Button, $Toggle, $Scene, $ToggleGroupElement, $SearchComponent, $Dialog, $ItemSlot, $TextArea, $GraphView, $BindableValue, $FluidSlot, $TextElement, $TabView } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements";
import { $ModularUITooltipComponent } from "@package/com/lowdragmc/lowdraglib2/gui/ui/utils";
import { $ColorPattern } from "@package/com/lowdragmc/lowdraglib2/gui";
import { $RPCEventBuilder } from "@package/com/lowdragmc/lowdraglib2/gui/sync/rpc";
import { $Duration } from "@package/java/time";
import { $BlockStateProperties } from "@package/net/minecraft/world/level/block/state/properties";
import { $AlmostKube } from "@package/com/almostreliable/unified/compat/kube";
import { $EMIUIEvents } from "@package/com/lowdragmc/lowdraglib2/integration/xei/emi";
import { $LanguageDefinition, $TokenType, $Languages } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements/codeeditor/language";
import { $LDKJSMenuTypes } from "@package/com/lowdragmc/lowdraglib2/integration/kjs/ui";
import { $SoundType, $Blocks } from "@package/net/minecraft/world/level/block";
import { $VillagerUtils, $TradeItem } from "@package/com/almostreliable/morejs/features/villager";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $Stats } from "@package/net/minecraft/stats";
import { $Matrix4f, $Vector4f, $Vector3f, $Quaternionf, $Matrix3f } from "@package/org/joml";
import { $DamageSource } from "@package/net/minecraft/world/damagesource";

declare module "@side-only/startup/bindings" {
}

export {};

declare global {
    let global: {};
    let Platform: typeof $PlatformWrapper;
    let console: $ConsoleJS;
    let JavaMath: typeof $Math;
    let ID: typeof $ID;
    let Duration: typeof $Duration;
    let KMath: typeof $KMath;
    let Utils: typeof $UtilsWrapper;
    let StringUtils: typeof $StringUtilsWrapper;
    let Java: typeof $JavaWrapper;
    let Text: typeof $TextWrapper;
    let Component: typeof $TextWrapper;
    let TextIcons: typeof $TextIcons;
    let UUID: typeof $UUIDWrapper;
    let JsonUtils: typeof $JsonUtils;
    let JsonIO: typeof $JsonIO;
    let Block: typeof $BlockWrapper;
    let Blocks: typeof $Blocks;
    let Item: typeof $ItemWrapper;
    let Items: typeof $Items;
    let Ingredient: typeof $IngredientWrapper;
    let NBT: typeof $NBTWrapper;
    let NBTIO: typeof $NBTIOWrapper;
    let Direction: typeof $DirectionWrapper;
    let Facing: typeof $DirectionWrapper;
    let AABB: typeof $AABBWrapper;
    let Stats: typeof $Stats;
    let FluidAmounts: typeof $FluidAmounts;
    let Notification: typeof $NotificationToastData;
    let SizedIngredient: typeof $SizedIngredientWrapper;
    let ParticleOptions: typeof $ParticleOptionsWrapper;
    let Registry: typeof $RegistryWrapper<any>;
    let DataMap: typeof $DataMapWrapper<any, any>;
    let EntitySelector: typeof $EntitySelectorWrapper;
    let Fluid: typeof $FluidWrapper;
    let SECOND: number;
    let MINUTE: number;
    let HOUR: number;
    let Color: typeof $ColorWrapper;
    let BlockStatePredicate: typeof $BlockStatePredicate;
    let Vec3d: typeof $Vec3;
    let Vec3i: typeof $Vec3i;
    let Vec3f: typeof $Vector3f;
    let Vec4f: typeof $Vector4f;
    let Matrix3f: typeof $Matrix3f;
    let Matrix4f: typeof $Matrix4f;
    let Quaternionf: typeof $Quaternionf;
    let RotationAxis: typeof $RotationAxis;
    let BlockPos: typeof $BlockPos;
    let DamageSource: typeof $DamageSource;
    let SoundType: typeof $SoundType;
    let BlockProperties: typeof $BlockStateProperties;
    let NativeEvents: typeof $NativeEventWrapper;
    let MobEffectUtil: typeof $MobEffectUtil;
    let Client: $Minecraft;
    let GLFWInput: $AbstractMap<any, any>;
    let XmlUtils: typeof $XmlUtils;
    let JEIUIEvents: typeof $JEIUIEvents;
    let EMIUIEvents: typeof $EMIUIEvents;
    let LDLib2UIFactory: typeof $LDKJSMenuTypes;
    let TreeBuilder: typeof $TreeBuilder<any, any>;
    let MenuBuilder: typeof $TreeBuilder$Menu;
    let ModularUITooltipComponent: typeof $ModularUITooltipComponent;
    let StylesheetManager: typeof $StylesheetManager;
    let Stylesheet: typeof $Stylesheet;
    let UIEvents: typeof $UIEvents;
    let UIEventListener: typeof $UIEventListener;
    let UIEventDispatcher: typeof $UIEventDispatcher;
    let HoverTooltips: typeof $HoverTooltips;
    let InventorySlots: typeof $InventorySlots;
    let TokenType: typeof $TokenType;
    let Languages: typeof $Languages;
    let LanguageDefinition: typeof $LanguageDefinition;
    let CodeEditor: typeof $CodeEditor;
    let UITemplateElement: typeof $UITemplateElement;
    let TreeList: typeof $TreeList<any>;
    let ToggleGroupElement: typeof $ToggleGroupElement;
    let Toggle: typeof $Toggle;
    let TextField: typeof $TextField;
    let TextElement: typeof $TextElement;
    let TextArea: typeof $TextArea;
    let TagField: typeof $TagField;
    let TabView: typeof $TabView;
    let Tab: typeof $Tab;
    let Switch: typeof $Switch;
    let SplitViewVertical: typeof $SplitView$Vertical;
    let SplitViewHorizontal: typeof $SplitView$Horizontal;
    let Selector: typeof $Selector<any>;
    let SearchComponent: typeof $SearchComponent<any>;
    let ScrollerView: typeof $ScrollerView;
    let ScrollerVertical: typeof $Scroller$Vertical;
    let ScrollerHorizontal: typeof $Scroller$Horizontal;
    let Scene: typeof $Scene;
    let ProgressBar: typeof $ProgressBar;
    let Menu: typeof $Menu<any, any>;
    let Label: typeof $Label;
    let ItemSlot: typeof $ItemSlot;
    let Inspector: typeof $Inspector;
    let GraphView: typeof $GraphView;
    let FluidSlot: typeof $FluidSlot;
    let Dialog: typeof $Dialog;
    let ColorSelector: typeof $ColorSelector;
    let Button: typeof $Button;
    let BindableValue: typeof $BindableValue<any>;
    let UIElement: typeof $UIElement;
    let UI: typeof $UI;
    let ModularUI: typeof $ModularUI;
    let VanillaSpriteTexture: typeof $VanillaSpriteTexture;
    let UIResourceTexture: typeof $UIResourceTexture;
    let TextTexture: typeof $TextTexture;
    let SpriteTexture: typeof $SpriteTexture;
    let ShaderTexture: typeof $ShaderTexture;
    let SDFRectTexture: typeof $SDFRectTexture;
    let RectTexture: typeof $RectTexture;
    let ItemStackTexture: typeof $ItemStackTexture;
    let IGuiTexture: typeof $IGuiTexture;
    let GuiTextureGroup: typeof $GuiTextureGroup;
    let FluidStackTexture: typeof $FluidStackTexture;
    let DynamicTexture: typeof $DynamicTexture;
    let ColorRectTexture: typeof $ColorRectTexture;
    let ColorBorderTexture: typeof $ColorBorderTexture;
    let AnimationTexture: typeof $AnimationTexture;
    let RPCEventBuilder: typeof $RPCEventBuilder;
    let SupplierDataSource: typeof $SupplierDataSource<any>;
    let ScrollDataSource: typeof $ScrollDataSource<any>;
    let DataBindingBuilder: typeof $DataBindingBuilder<any>;
    let LocalSlot: typeof $LocalSlot;
    let ItemHandlerSlot: typeof $ItemHandlerSlot;
    let ColorPattern: typeof $ColorPattern;
    let UIResource: typeof $UIResource;
    let TexturesResource: typeof $TexturesResource;
    let IRendererResource: typeof $IRendererResource;
    let ColorsResource: typeof $ColorsResource;
    let ClipboardManager: typeof $ClipboardManager;
    let PLAYER_UI: $DeferredHolder<any, any>;
    let Vector3f: typeof $Vector3f;
    let GuiSize: typeof $Size;
    let GuiPos: typeof $Position;
    let coeutil: typeof $COEUtil;
    let VillagerUtils: typeof $VillagerUtils;
    let TradeItem: typeof $TradeItem;
    let MoreUtils: typeof $MoreJSBinding;
    let EnchantmentInstance: typeof $EnchantmentInstance;
    let CreateItem: typeof $KubeCreateOutput;
    let CreateProcessingOutput: typeof $ProcessingOutput;
    let CastingOutput: typeof $CastingOutputWrapper;
    let EntityIngredient: typeof $EntityIngredientWrapper;
    let AlmostUnified: typeof $AlmostKube;
}
