ServerEvents.recipes(event => {
    event.remove({ output: 'mymod:closed_scroll'})
})

MoreJS.villagerTrades(event => {
    event.removeModdedTypedTrades(["minecraft:librarian"])
})
RecipeViewerEvents.removeEntriesCompletely('item',event => {
    event.remove('mymod:airbamb')
    event.remove('mymod:airbambdown')
    event.remove('mymod:balanced_water_spawn_egg')
    event.remove('mymod:bend_1')
    event.remove('mymod:bend_3')
    event.remove('mymod:bend_4')
    event.remove('mymod:bend_5')
    event.remove('mymod:bend_7')
    event.remove('mymod:closed_air_scroll')
    event.remove('mymod:closed_earth_scroll')
    event.remove('mymod:closed_fire_scroll')
    event.remove('mymod:closed_scroll')
    event.remove('mymod:closed_water_scroll')
    event.remove('mymod:deactivated_earth_core')
    event.remove('mymod:earthcore')
    event.remove('mymod:earthfirefly_spawn_egg')
    event.remove('mymod:earthy_beatle_spawn_egg')
    event.remove('mymod:flow_spawn_egg')
    event.remove('mymod:flying_blocks_spawn_egg')
    event.remove('mymod:garrgoyle')
    event.remove('mymod:open_air_scroll')
    event.remove('mymod:open_earth_scroll')
    event.remove('mymod:open_water_scroll')
    event.remove('mymod:open_fire_scroll')
    event.remove('mymod:open_scroll')
    event.remove('mymod:pieceofancientlore')
    event.remove('mymod:shieldy_spawn_egg')
    event.remove('mymod:water_club')
})