//This file was generated by Visual Recipe Editor by KrupicovaKase
//!!! Any user made change may get overwritten!!!
//To make changes, delete the recipe from this file and copy it somewhere else!
ServerEvents.recipes(event => {
   event.remove({id: 'rocketnautics:crafting/equipment/jetpack'})
   event.shaped(Item.of("rocketnautics:jetpack",1),
       [" B ",
       "DEF",
       "GHI"],

      {       B:"create:precision_mechanism",
       D:"rocketnautics:titanium_sheet",
      E:"create:netherite_backtank",
      F:"rocketnautics:titanium_sheet",
      G:"rocketnautics:titanium_nozzle",
      H:"cregalatla:dead_wings",
      I:"rocketnautics:titanium_nozzle"})
   event.remove({id: 'create_sa:brass_jetpack_recipe'})
   event.recipes.create.mechanical_crafting(Item.of("create_sa:brass_jetpack_chestplate",1),
      ["ABCDE",
       "FGHIJ",
       " LMN ",
       "     ",
       "     "],

      {A:"create:cogwheel",
      B:"create:brass_ingot",
      C:"create:cogwheel",
      D:"create:brass_ingot",
      E:"create:cogwheel",
      F:"create:encased_fan",
      G:"create:brass_ingot",
      H:"create:precision_mechanism",
      I:"create:brass_ingot",
      J:"create:encased_fan",
       L:"create:brass_ingot",
      M:"cregalatla:dead_wings",
      N:"create:brass_ingot",
          })
   event.remove({id: 'create_sa:andesite_jetpack_recipe'})
   event.recipes.create.mechanical_crafting(Item.of("create_sa:andesite_jetpack_chestplate",1),
      ["ABCDE",
       "FGHIJ",
       "KLMNO",
       "     ",
       "     "],

      {A:"create:cogwheel",
      B:"create:andesite_alloy",
      C:"create:belt_connector",
      D:"create:andesite_alloy",
      E:"create:cogwheel",
      F:"create:encased_fan",
      G:"create:andesite_alloy",
      H:"create_sa:heat_engine",
      I:"create:andesite_alloy",
      J:"create:encased_fan",
      K:"create:encased_fan",
      L:"create:zinc_ingot",
      M:"cregalatla:dead_wings",
      N:"create:zinc_ingot",
      O:"create:encased_fan",
         })
   event.remove({id: 'create_sa:copper_propeler_recipe'})
   event.shaped(Item.of("create_sa:copper_jetpack_chestplate",1),
       ["ABC",
       "DEF",
       "GHI"],

      {A:"minecraft:copper_ingot",
      B:"create:cogwheel",
      C:"minecraft:copper_ingot",
      D:"minecraft:copper_ingot",
      E:"create_sa:hydraulic_engine",
      F:"minecraft:copper_ingot",
      G:"create:fluid_tank",
      H:"cregalatla:dead_wings",
      I:"create:fluid_tank"})

}) //-closefile-